var quotesArray = [
	["A doubtful friend is worse than a certain enemy. Let a man be one thing or the other, and we then know how to meet him.", "Aesop"],
	["A foolish consistency is the hobgoblin of little minds.", "Ralph Waldo Emerson"],
	["A good act does not wash out the bad, nor a bad act the good. Each should have its own reward.", "Stannis Baratheon, A Clash of Kings"],
	["A good novel tells us the truth about its hero; but a bad novel tells us the truth about its author.", "G. K. Chesterton"],
	["A liar will not be believed even when he speaks the truth.", "Aesop"],
	["A man chooses, a slave obeys.", "Andrew Ryan, Bioshock"],
	["A man is no less a slave because he is allowed to choose a new master once in a term of years.", "Lysander Spooner"],
	["A man who won't be blackmailed can't be blackmailed.", "Robert A. Heinlein"],
	["A man's character is most evident by how he treats those who are not in a position either to retaliate or reciprocate.", "Paul Eldridge"],
	["A reader lives a thousand lives before he dies. The man who never reads lives only one.", "Jojen, A Dance with Dragons"],
	["A room without books is like a body without a soul.", "Marcus Tullius Cicero"],
	["Advice most needed is least heeded.", "Proverb"],
	["After all is said and done, more is said than done.", "Aesop"],
	["All the great things are simple, and many can be expressed in a single word: faith, freedom, justice, honor, duty, loyalty, mercy, hope.", "Winston Churchill"],
	["Always keep your foes confused. If they are never certain who you are or what you want, they cannot know what you are like to do next. Sometimes the best way to baffle them is to make moves that have no purpose, or even seem to work against you.", "Petyr Baelish, A Storm of Swords,"],
	["An open mind is like a fortress with its gates unbarred and unguarded.", "Librarian, Dawn of War"],
	["An ounce of prevention is worth a pound of cure.", "Benjamin Franklin"],
	["And we now find, that it is not only right to strike while the iron is hot, but that it may be very practicable to heat it by continually striking.", "Benjamin Franklin"],
	["As above, so below.", "Emerald Tablet"],
	["As iron sharpens iron, so too does one man sharpen another.", "Proverbs 27:17"],
	["As soon as men decide that all means are permitted to fight an evil, then their good becomes indistinguishable from the evil that they set out to destroy.", "Christopher Dawson"],
	["Ask not the sparrow how the eagle soars.", "Satsuki Kiryuin, Kill la Kill"],
	["Assumptions are like weeds. Best pull 'em up before they dig too deep.", "Proverb"],
	["Be extremely subtle, even to the point of formlessness. Be extremely mysterious, even to the point of soundlessness. Thereby you can be the director of the opponent's fate.", "Sun Tzu"],
	["Be peaceful, be courteous, obey the law, respect everyone; but if someone puts his hand on you, send him to the cemetery.", "Malcolm X"],
	["Be pitiful, for every man is fighting a hard battle", "Ian Maclaren"],
	["Be polite, be professional, but have a plan to kill everyone you meet.", "James Mattis"],
	["Before I had studied Zen for thirty years, I saw mountains as mountains, and waters as waters. When I arrived at a more intimate knowledge, I came to the point where I saw that mountains are not mountains, and waters are not waters. But now that I have got its very substance I am at rest. For it's just that I see mountains once again as mountains, and waters once again as waters.", "Qingyuan Weixin"],
	["Before you embark on a journey of revenge, dig two graves.", "Confucius"],
	["Better be wise by the misfortunes of others than by your own.", "Aesop"],
	["Beware of unearned wisdom.", "Carl Jung"],
	["Beware that, when fighting monsters, you yourself do not become a monster... for when you gaze long into the abyss. The abyss gazes also into you.", "Friedrich Nietzsche"],
	["But though we strike at you from the shadows, do not think we lack the courage to stand in the light.", "Zeratul, StarCraft"],
	["Computers are like Old Testament gods: lots of rules and no mercy.", "Joseph Campbell"],
	["Do or do not, there is no try.", "Yoda, The Empire Strikes Back"],
	["Don't ever take a fence down until you know the reason it was put up.", "G. K. Chesterton"],
	["Don't fight a battle if you don't gain anything by winning.", "Erwin Rommel"],
	["Don't lose your way", "Proverb"],
	["Education is the best provision for old age.", "Aristotle"],
	["Even brute beasts and wandering birds do not fall for the same traps or nets twice.", "Saint Jerome"],
	["Even fools are thought wise if they keep silent, and discerning if they hold their tongues.", "Proverbs 17:28"],
	["Every normal man must be tempted, at times, to spit on his hands, hoist the black flag, and begin slitting throats.", "H. L. Mencken"],
	["Everything should be made as simple as possible, but not simpler.", "Albert Einstein"],
	["Extremism in the defense of liberty is no vice. And let me remind you also that moderation in the pursuit of justice is no virtue.", "Barry Goldwater"],
	["Fortune favours the bold.", "Turnus, The Aeneid"],
	["From everyone who has been given much, much will be demanded; and from the one who has been entrusted with much, much more will be asked.", "Luke 12:48"],
	["Give a man a mask and he will show his true face.", "Oscar Wilde"],
	["Happiness: a good bank account, a good cook and a good digestion", "Jean Jacques Rousseau"],
	["He who destroys a good book kills reason itself", "John Milton"],
	["He who has lost honor can lose nothing more", "Publilius Syrus"],
	["He who knows others is wise; He who know himself is enlightened", "Laozi"],
	["He who wishes to be obeyed must know how to command", "Niccolo Machiavelli"],
	["Heav'n has no rage, like love to hatred turn'd<br>Nor hell a fury, like a woman scorn'd.", "Zara, The Mourning Bride"],
	["Her lips said no, but her eyes said read my lips.", "Niles Crane, Frasier"],
	["Honesty is the best policy; I will stick to that. The good shall have my hand and heart; but the bad neither foot nor friendship.", "Sancho Panza, Don Quixote"],
	["Honor is simply the morality of superior men.", "H. L. Mencken"],
	["I fear not the man who has practiced 10,000 kicks once, but I fear the man who has practiced one kick 10,000 times.", "Bruce Lee"],
	["I find the great thing in this world is not so much where we stand, as in what direction we are moving.", "Oliver Wendell Holmes"],
	["I have not yet begun to fight!", "John Paul Jones"],
	["I never think of the future, it comes soon enough.", "Albert Einstein"],
	["I'll never be frightened of shepherds. It's the sheep who trouble me.", "Petyr Baelish, A Clash of Kings"],
	["If one wishes not to be handled, one should not grow a handle.", "Jiu Jitsu Proverb"],
	["If people can't control their own emotions, then they have to start trying to control other people's behavior.", "John Cleese"],
	["If they stand behind you, give them protection. If the stand beside you, give them respect. If they stand against you, show them no mercy.", "Unknown"],
	["If you can question it, it's science. If you can't, it's propaganda.", "Unknown"],
	["If you want peace, prepare for war.", "Latin Proverb"],
	["If you want to change the world, pick up your pen and write.", "Martin Luther"],
	["If you're going through hell, keep going.", "Winston Churchill"],
	["In debates between anarchists and statists, the burden of proof clearly should rest on those who place their trust in the state. Anarchy's mayhem is wholly conjectural; the state's mayhem is undeniably, factually horrendous.", "Robert Higgs"],
	["In nothing do men more nearly approach the gods than in giving health to men.", "Marcus Tullius Cicero"],
	["In preparing for battle I have always found that plans are useless, but planning is indispensable.", "Dwight Eisenhower"],
	["In sterquiliniis invenitur (in filth it shall be found).", "Carl Jung"],
	["In the game of thrones, even the humblest pieces can have wills of their own. Sometimes they refuse to make the moves you've planned for them.", "Petyr Baelish"],
	["It all goes back and back, to our mothers and fathers and theirs before them. We are puppets dancing on the strings of those who came before us, and one day our own children will take up our strings and dance in our steads.", "Tyrion Lannister"],
	["It is better to be feared than loved, if you cannot be both.", "Niccolo Machiavelli"],
	["It is better to keep your mouth closed and let people think you are a fool than to open it and remove all doubt.", "Mark Twain"],
	["It is difficult to get a man to understand something, when his salary depends on his not understanding it.", "Upton Sinclair"],
	["It is not light that we need, but fire; it is not the gentle shower, but thunder. We need the storm, the whirlwind, and the earthquake.", "Frederick Douglass"],
	["It is well that war is so terrible, otherwise we should grow too fond of it.", "Robert E. Lee"],
	["It's our wits that make us men.", "Malcolm Wallace, Braveheart"],
	["Just because you're paranoid doesn't mean they aren't after you.", "Captain John Yossarian, Catch-22"],
	["Learn to obey before you command", "Solon"],
	["Liberty is not the daughter, but the mother of order.", "Pierre-Joseph Proudhon"],
	["Life is too important to be taken seriously.", "Oscar Wilde"],
	["Live free or die: Death is not the worst of evils.", "John Stark"],
	["Loyal service means telling hard truths.", "Davos Seaworth, Game of Thrones"],
	["Measure what is measurable, and make measurable what is not so.", "Galileo Galilei"],
	["Men of honor will do things for their children that they would never consider doing for themselves.", "Petyr Baelish, A Feast for Crows"],
	["Never interrupt your enemy when he is making a mistake.", "Napoleon Bonaparte"],
	["No tree, it is said, can grow to heaven unless its roots reach down to hell.", "Carl Jung"],
	["No-one is equal to anything. Even the same man is not equal to himself on different days.", "Thomas Sowell"],
	["Nothing is particularly hard if you divide it into small jobs.", "Henry Ford"],
	["Of all tyrannies, a tyranny sincerely exercised for the good of its victims may be the most oppressive. It would be better to live under robber barons than under omnipotent moral busybodies. The robber baron's cruelty may sometimes sleep, his cupidity may at some point be satiated; but those who torment us for our own good will torment us without end for they do so with the approval of their own conscience.", "C. S. Lewis"],
	["Of old the expert in battle would first make himself invincible and then wait for his enemy to expose his vulnerability.", "Sun Tzu"],
	["One must not tie a ship to a single anchor, nor life to a single hope.", "Epictetus"],
	["Only a fool learns from his own mistakes. The wise man learns from the mistakes of others.", "Otto von Bismarck"],
	["Only a warrior chooses pacifism; others are condemned to it.", "Eduardo Garcia"],
	["Our cruel and unrelenting enemy leaves us no choice but a brave resistance, or the most abject submission; this is all we can expect. We have therefore to resolve to conquer or die.", "George Washington"],
	["Our scientific power has outrun our spiritual power. We have guided missiles and misguided men.", "Martin Luther King, Jr."],
	["Pale Death beats equally at the poor man's gate and at the palaces of kings.", "Horace"],
	["Perfection is achieved, not when there is nothing more to add, but when there is nothing left to take away.", "Antoine de Saint-Exupery"],
	["Power resides where men believe it resides, it's a trick, a shadow on the wall. And a very small man can cast a very large shadow.", "Varys, A Clash of Kings"],
	["Rome wasn't built in a day.", "Proverb"],
	["Rules are for children. This is war, and in war the only crime is to lose.", "Bayaz, Last Argument of Kings"],
	["Show me the man and I'll show you the crime", "Lavrentiy Beria"],
	["Some ideas are so stupid that only intellectuals believe them.", "George Orwell"],
	["The average man does not want to be free. He simply wants to be safe.", "H. L. Mencken"],
	["The mass of men lead lives of quiet desperation.", "Henry David Thoreau"],
	["The obedient always think about themselves as virtuous, rather than cowardly.", "Robert Anton Wilson"],
	["The role of a writer is not to say what we can all say, but what we are unable to say.", "Anais Nin"],
	["The society that separates its scholars from its warriors will have its thinking done by cowards and its fighting by fools.", "Thucydides"],
	["The tree of liberty must be refreshed from time to time with the blood of patriots and tyrants.", "Thomas Jefferson"],
	["The tyrant will always find a pretext for his tyranny, and it is useless for the innocent to try by reasoning to get justice, when the oppressor intends to be unjust.", "Aesop"],
	["The urge to save humanity is almost always a false front for the urge to rule.", "H. L. Mencken"],
	["The victorious strategist only seeks battle after the victory has been won, whereas he who is destined to defeat first fights and afterwards looks for victory.", "Sun Tzu"],
	["The weak are always anxious for justice and equality. The strong pay no heed to either.", "Aristotle"],
	["The weakest of all weak things is a virtue that has not been tested in the fire.", "Mark Twain"],
	["The wise tell us that a nail keeps a shoe, a shoe keeps a horse, a horse keeps a knight, a knight, who can fight, keeps a castle.	", "Freidank"],
	["There are no two words in the English language more harmful than good job.", "Terence Fletcher, Whiplash"],
	["There can be no true despair without hope.", "Bane, The Dark Knight Rises"],
	["There is a great deal of ruin in a nation.", "Adam Smith"],
	["There is no better than adversity. Every defeat, every heartbreak, every loss, contains its own seed, its own lesson on how to improve your performance next time.", "Malcolm X"],
	["There is no female Mozart because there is no female Jack the Ripper.", "Camille Paglia"],
	["There is nothing noble in being superior to your fellow man; true nobility is being superior to your former self.", "Ernest Hemmingway"],
	["There is only one good, knowledge, and one evil, ignorance.", "Socrates"],
	["Those that rule must hear and be deaf, must see and be blind", "German Proverb"],
	["Those who cannot remember the past are condemned to repeat it.", "George Santayana"],
	["Those who need leaders are not qualified to choose them.", "Michael Malice"],
	["Thou salt not muzzle the ox when he treadeth out the corn.", "Deuteronomy, 25:4"],
	["Three things are necessary for the salvation of man: to know what he ought to believe; to know what he ought to desire; and to know what he ought to do.", "Saint Thomas Aquinas"],
	["Three things are to be looked to in a building: that it stand on the right spot; that it be securely founded; that it be successfully executed.", "Johann Wolfgang von Goethe"],
	["Time crumbles things; everything grows old and is forgotten under the power of time.", "Aristotle"],
	["To achieve great things, two things are needed: a plan, and not quite enough time.", "Leonard Bernstein"],
	["To err is human, to forgive divine.", "Alexander Pope"],
	["To fight and conquer in all your battles is not supreme excellence; supreme excellence consists in breaking the enemy's resistance without fighting.", "Sun Tzu"],
	["Tomorrow can redeem any failure and it can undermine any success.", "John Danaher"],
	["Tradition is not the worship of ashes but the preservation of fire.", "Gustav Mahler"],
	["Treade a worme on the tayle, and it must turne agayne.", "John Heywood"],
	["Truth is treason in an empire of lies.", "George Orwell"],
	["Truth, she thought. As terrible as death. But harder to find.", "Juliana  Crain, The Man in the High Castle"],
	["Uneasy lies the head that wears a crown", "King Henry IV, Henry IV, Part 2."],
	["Violence sings its own song.", "Michael Malice"],
	["War is cruelty. There is no use trying to reform it. The crueler it is, the sooner it will be over.", "William Tecumseh Sherman"],
	["War is merely the continuation of politics by other means.", "Carl von Clausewitz"],
	["War is nothing but a duel on a larger scale.", "Carl von Clausewitz"],
	["War therefore is an act of violence to compel our opponent to fulfill our will.", "Carl von Clausewitz"],
	["We do not choose our destinies. Yet we must… we must do our duty, no? Great or small, we must do our duty.", "Stannis Baratheon, A Storm of Swords"],
	["We hang the petty thieves and appoint the great ones to public office.", "Aesop"],
	["We have now sunk to a depth at which restatement of the obvious is the first duty of intelligent men.", "George Orwell"],
	["We often give our enemies the means for our own destruction.", "Aesop"],
	["Well begun is half done.", "Aristotle"],
	["What has been will be again,<br>what has been done will be done again;<br>there is nothing new under the sun.", "Ecclesiastes 1:9"],
	["What we obtain too cheap, we esteem too lightly; it is dearness only that gives everything its value.", "Thomas Paine"],
	["What you see and what you hear depends a great deal on where you are standing. It also depends on what sort of person you are.", "C. S. Lewis"],
	["When a dog goes bad, the fault lies with his master.", "Kevan Lannister, A Feast for Crows"],
	["When a dove begins to associate with crows its feathers remain white but its heart grows black.", "German Proverb"],
	["When goods don't cross borders, soldiers will.", "Frederic Bastiat"],
	["When injustice becomes law, rebellion becomes duty.", "Thomas Jefferson"],
	["When people get used to preferential treatment, equal treatment seems like discrimination.", "Thomas Sowell"],
	["When the snows fall and the white winds blow, the lone wolf dies but the pack survives.", "Eddard Stark, A Game of Thrones"],
	["When you pray for rain, you gotta deal with the mud too.", "Robert McCall, The Equalizer"],
	["When your enemies defy you, you must serve them steel and fire. When they go to their knees, however, you must help them back to their feet. Elsewise no man will ever bend the knee to you.", "Tywin Lannister, A Storm of Swords"],
	["Where the battle rages, there the loyalty of the soldier is proved.", "Martin Luther"],
	["Where there are too many policemen, there is no liberty. Where there are too many soldiers, there is no peace. Where there are too many lawyers, there is no justice.", "Lin Yutang"],
	["Where there is only a choice between cowardice and violence, I would advise violence.", "Mohandas Gandhi"],
	["Wherever we look, the work of the chemist has raised the level of our civilization and has increased the productive capacity of our nation.", "Calvin Coolidge"],
	["With each passing day, the world finds new and exciting ways to kill a man.", "Balthier, Final Fantasy XII"],
	["You can't cheat an honest man.", "Proverb"],
	["You should laugh every moment you live, for you'll find it decidedly difficult afterwards.", "Joe Abercrombie, Best Served Cold"],
	["‘We need’ is always code for ‘I want.’", "Michael Malice"]
];
function displayQuote() {
	var rand = Math.floor(Math.random() * (quotesArray.length));
	document.getElementById('quote').innerHTML = "<h2>\"" + quotesArray[rand][0] + "\"</h2>" + "-" + quotesArray[rand][1];
}