var quotesArray = [
    ["'Tis your birth and faith that wrong you...not I.", "Delita Heiral, Final Fantasy Tactics"],
    ["A bag of dragons buys a man's silence for a while, but a well-placed quarrel buys it forever.", "Petyr Baelish, A Storm of Swords"],
    ["A doubtful friend is worse than a certain enemy. Let a man be one thing or the other, and we then know how to meet him.", "Aesop"],
    ["A fire broke out backstage in a theatre. The clown came out to warn the public; they thought it was a joke and applauded. He repeated it; the acclaim was even greater. I think that's just how the world will come to an end: to general applause from wits who believe it's a joke.", "Soren Kierkegaard"],
    ["A foolish consistency is the hobgoblin of little minds.", "Ralph Waldo Emerson"],
    ["A friend of death, a brother of luck, and a son of a bitch.", "Elim Rawne of Ibram Gaunt, Necropolis"],
    ["A good act does not wash out the bad, nor a bad act the good. Each should have its own reward.", "Stannis Baratheon, A Clash of Kings"],
    ["A good novel tells us the truth about its hero; but a bad novel tells us the truth about its author.", "G. K. Chesterton"],
    ["A good rule for rocket experimenters to follow is this: always assume that it will explode.", "Astronautics Magazine, 1937"],
    ["A human being should be able to change a diaper, plan an invasion, butcher a hog, conn a ship, design a building, write a sonnet, balance accounts, build a wall, set a bone, comfort the dying, take orders, give orders, cooperate, act alone, solve equations, analyse a new problem, pitch manure, program a computer, cook a tasty meal, fight efficiently, die gallantly. Specialization is for insects.", "Robert A. Heinlein"],
    ["A liar will not be believed even when he speaks the truth.", "Aesop"],
    ["A life of wealth and privilege has left you blind in one eye. You are the few, we are the many, and when the many stop fearing the few.", "High Sparrow to Olenna Tyrell, Game of Thrones"],
    ["A lion doesn't concern himself with the opinions of the sheep.", "Tywin Lannister, Game of Thrones"],
    ["A long habit of not thinking a thing wrong gives it a superficial appearance of being right.", "Thomas Paine"],
    ["A man chooses, a slave obeys.", "Andrew Ryan, Bioshock"],
    ["A man is no less a slave because he is allowed to choose a new master once in a term of years.", "Lysander Spooner"],
    ["A man is nothing but a man, But before I let your steam drill beat me down, I'd die with a hammer in my hand.", "Anonymous, John Henry"],
    ["A man lost in the desert must take such water as he is offered, no matter who it comes from.", "Haddish Kahdia, Before They Are Hanged"],
    ["A man who won't be blackmailed can't be blackmailed.", "Robert A. Heinlein"],
    ["A man without friends is a man without power.", "Renly Baratheon, A Clash of Kings"],
    ["A man's character is most evident by how he treats those who are not in a position either to retaliate or reciprocate.", "Paul Eldridge"],
    ["A map is not the territory it represents, but, if correct, it has a similar structure to the territory, which accounts for its usefulness.", "Alfred Korzybski"],
    ["A reader lives a thousand lives before he dies. The man who never reads lives only one.", "Jojen, A Dance with Dragons"],
    ["A room without books is like a body without a soul.", "Marcus Tullius Cicero"],
    ["A ruler must learn to persuade and not to compel.", "Paul Atreides, Dune"],
    ["A ship in harbor is safe, but that is not what ships are built for.", "John A. Shedd"],
    ["A smuggler must be a fair judge of men.", "Stannis Baratheon to Davos Seaworth, A Clash of Kings"],
    ["A time is coming when men will go mad, and when they see someone who is not mad, they will attack him, saying, ‘You are mad; you are not like us.’", "St. Anthony the Great"],
    ["A wise man can learn more from a foolish question than a fool can learn from a wise answer.", "Bruce Lee"],
    ["A word spoken is past recalling. Deeds are fruits, words are but leaves.", "Proverb"],
    ["A word to the wise is enough, and many words won't fill a bushel.", "Benjamin Franklin"],
    ["Absence of evidence is not evidence of absence.", "Aphorism"],
    ["Accept me and I shall grant life everlasting. Though it shall be filled with grief, thou shalt have all eternity to wreak vengeance upon thine enemies.", "Lester DeRosso, Bravely Default"],
    ["Advice most needed is least heeded.", "Proverb"],
    ["After all is said and done, more is said than done.", "Aesop"],
    ["After all, no one is stupid enough to prefer war to peace; in peace sons bury their fathers and in war fathers bury their sons.", "Herodotus"],
    ["Alea iacta est (The die has been cast).", "Julius Caesar upon crossing the Rubicon"],
    ["Alexander the Great and his mule driver both died and the same thing happened to both. They were absorbed alike into the life force of the world, or dissolved alike into atoms.", "Marcus Aurelius"],
    ["All governments suffer a recurring problem: Power attracts pathological personalities. It is not that power corrupts but that it is magnetic to the corruptible. Such people have a tendency to become drunk on violence, a condition to which they are quickly addicted.", "Frank Herbert"],
    ["All great men are play actors of their own ideal.", "Friedrich Nietzsche"],
    ["All is fair in love and war.", "John Lyly, Euphues"],
    ["All men are fools, if truth be told, but the ones in motley are more amusing than ones with crowns.", "Olenna Tyrell, A Storm of Swords"],
    ["All stories are true. But this one really happened, if that's what you mean.", "Skarpi, The Name of the Wind"],
    ["All the great things are simple, and many can be expressed in a single word: faith, freedom, justice, honor, duty, loyalty, mercy, hope.", "Winston Churchill"],
    ["All the world's a stage,<br>And all the men and women merely players;", "Jaques, As You Like It"],
    ["All warfare is based on deception. Hence, when able to attack, we must seem unable; when using our forces, we must seem inactive; when we are near, we must make the enemy believe we are far away; when far away, we must make him believe we are near. Hold out baits to entice the enemy. Feign disorder, and crush him.", "Sun Tzu"],
    ["Always keep your foes confused. If they are never certain who you are or what you want, they cannot know what you are like to do next. Sometimes the best way to baffle them is to make moves that have no purpose, or even seem to work against you.", "Petyr Baelish, A Storm of Swords,"],
    ["Amateurs talk about tactics, but professionals study logistics.", "Proverb"],
    ["Americans will not tolerate a loser. The very idea of losing is hateful to an American.", "George S. Patton"],
    ["An ant has no quarrel with a boot.", "Loki, The Avengers"],
    ["An open mind is all very well in its way, but it ought not to be so open that there is no keeping anything in or out of it", "Samuel Butler"],
    ["An open mind is like a fortress with its gates unbarred and unguarded.", "Librarian, Dawn of War"],
    ["An orator without judgment is a horse without a bridle.", "Theophrastus"],
    ["An ounce of prevention is worth a pound of cure.", "Benjamin Franklin"],
    ["And I say also unto thee, That thou art Peter, and upon this rock I will build my church; and the gates of hell shall not prevail against it.", "Matthew 16:18"],
    ["And I tell you, you are Peter, and on this rock I will build my church, and the gates of hell shall not prevail against it. 19 I will give you the keys of the kingdom of heaven, and whatever you bind on earth shall be bound in heaven, and whatever you loose on earth shall be loosed in heaven.", "Matthew 16:18-19"],
    ["And he said unto them, Render therefore unto Caesar the things which be Caesar's, and unto God the things which be God's.", "Luke 20:25"],
    ["And he shall judge among the nations, and shall rebuke many people: and they shall beat their swords into plowshares, and their spears into pruninghooks: nation shall not lift up sword against nation, neither shall they learn war any more.", "Isaiah 2:4"],
    ["And lo! How brightly burned their lanthorn! Casts it back the shadow of Occurian design! Testament that Man's history shall be his alone!", "Dr. Cid, Final Fantasy XII"],
    ["And so here at the end of my life, I do once again betray a former master. The path ahead is fraught with peril. But I will do all I can to keep it stable - keep you safe. I'm not so foolish to think this will absolve me of my sins. One life hardly balances billions.", "Mendicant Bias, Halo 3"],
    ["And those people should not be listened to who keep saying the voice of the people is the voice of God, since the riotousness of the crowd is always very close to madness.", "Alcuin of York"],
    ["And we now find, that it is not only right to strike while the iron is hot, but that it may be very practicable to heat it by continually striking.", "Benjamin Franklin"],
    ["And what he greatly thought, he nobly dared.", "Athena to Telemachus, The Odyssey"],
    ["And when they seek to oppress you, And when they try to destroy you, rise and rise again and again, like the phoenix from the ashes, until the lambs have become lions and the rule of darkness is no more.", "Maitreya, The Friend of All Souls"],
    ["And why beholdest thou the mote that is in thy brother's eye, but considerest not the beam that is in thine own eye?", "Matthew 7:3"],
    ["Another parable put he forth unto them, saying, The kingdom of heaven is likened unto a man which sowed good seed in his field. But while men slept, his enemy came and sowed tares among the wheat, and went his way.", "Matthew 13:24-25"],
    ["Any man who must say, ‘I am the king’ is no true king. I'll make sure you understand that when I've won your war for you.", "Tywin Lannister, Game of Thrones"],
    ["Appearances can be deceiving.", "English Proverb"],
    ["Architecture has recorded the great ideas of the human race. Not only every religious symbol, but every human thought has its page in that vast book.", "Victor Hugo"],
    ["Art is not a democracy. People don't get to vote on how it ends.", "George R. R. Martin"],
    ["Artists use lies to tell the truth.", "V, V for Vendetta"],
    ["As above, so below.", "Emerald Tablet"],
    ["As soon as men decide that all means are permitted to fight an evil, then their good becomes indistinguishable from the evil that they set out to destroy.", "Christopher Dawson"],
    ["Ask not the sparrow how the eagle soars.", "Satsuki Kiryuin, Kill la Kill"],
    ["Assumptions are like weeds. Best pull 'em up before they dig too deep.", "Proverb"],
    ["At times, the joy that life attacks me with is unbearable and leads to gasping hysterical laughter. I find myself completely out of control and wonder how life could surprise me again and again and again, so completely. How could a man be a cynic? It is a sin.", "Norm Macdonald"],
    ["Audentis Fortuna iuvat (Fortune favours the bold).", "Latin Proverb"],
    ["Be extremely subtle, even to the point of formlessness. Be extremely mysterious, even to the point of soundlessness. Thereby you can be the director of the opponent's fate.", "Sun Tzu"],
    ["Be peaceful, be courteous, obey the law, respect everyone; but if someone puts his hand on you, send him to the cemetery.", "Malcolm X"],
    ["Be pitiful, for every man is fighting a hard battle.", "Ian Maclaren"],
    ["Be polite, be professional, but have a plan to kill everyone you meet.", "James Mattis"],
    ["Be yourself; everyone else is already taken.", "Oscar Wilde"],
    ["Beauty in things exists in the mind which contemplates them.", "David Hume"],
    ["Before I had studied Zen for thirty years, I saw mountains as mountains, and waters as waters. When I arrived at a more intimate knowledge, I came to the point where I saw that mountains are not mountains, and waters are not waters. But now that I have got its very substance I am at rest. For it's just that I see mountains once again as mountains, and waters once again as waters.", "Qingyuan Weixin"],
    ["Before you embark on a journey of revenge, dig two graves.", "Confucius"],
    ["Behind the rock in the dark probably hides a tiger, and the coiling giant root resembles a crouching dragon.", "Yu Xin"],
    ["Being powerful is like being a lady. If you have to tell people you are, you aren't.", "Margaret Thatcher"],
    ["Betray a friend, and you'll often find you have ruined yourself.", "Aesop"],
    ["Better a diamond with a flaw than a pebble without.", "Confucius"],
    ["Better be wise by the misfortunes of others than by your own.", "Aesop"],
    ["Better is bread with a happy heart than wealth with vexation.", "Pharaoh Amenemope"],
    ["Better to be a warrior in a garden than a gardener in a war.", "Chinese Proverb"],
    ["Beware of false prophets, which come to you in sheep's clothing, but inwardly they are ravening wolves.", "Matthew 7:15"],
    ["Beware of unearned wisdom.", "Carl Jung"],
    ["Beware that, when fighting monsters, you yourself do not become a monster...for when you gaze long into the abyss, the abyss gazes also into you.", "Friedrich Nietzsche"],
    ["Bill: How did you go bankrupt?<br>Mike: Two ways. Gradually, then suddenly.", "The Sun Also Rises"],
    ["Bleh! You people make me sick! You sound like lines from a self-help book! If that's how it's going to be...I'll snuff them all out! Every last one of your sickening, happy little reasons for living!", "Kefka Palazzo, Final Fantasy VI"],
    ["Blood for the Blood God! Skulls for the Skull Throne!", "Khornate Warcry, Warhammer 40,000"],
    ["Books are a uniquely portable magic.", "Stephen King"],
    ["Broken people break people.", "Unknown"],
    ["Brothers, what we do in life echoes in eternity.", "Maximus Decimus Meridius, Gladiator"],
    ["Bushido is realized in the presence of death. This means choosing death whenever there is a choice between life and death. There is no other reasoning.", "Yamamoto Tsunetomo"],
    ["But it did no good to brood on lost battles and roads not taken. That was a vice of old done men.", "Kevan Lannister, A Dance with Dragons"],
    ["But though we strike at you from the shadows, do not think we lack the courage to stand in the light.", "Zeratul, StarCraft"],
    ["By what right does the wolf judge the lion?", "Jaime Lannister, Game of Thrones"],
    ["Cause every once in a while, the lion has to show the jackals, who he is.", "Uncle Mike, Poolhall Junkies"],
    ["Christianity has died many times and risen again; for it had a God who knew the way out of the grave.", "G. K. Chesterton"],
    ["Colonel Graff: Tell me why you kept on kicking him. You had already won.<br>Ender Wiggin: Knocking him down won the first fight. I wanted to win all the next ones, too.", "Ender's Game"],
    ["Come unto me, all ye that labour and are heavy laden, and I will give you rest.", "Matthew 11:28"],
    ["Comedy aims at representing men as worse, Tragedy as better than in actual life.", "Aristotle"],
    ["Comfort is the enemy of achievement.", "Farrah Gray"],
    ["Comparison is the thief of joy.", "Theodore Roosevelt"],
    ["Compound interest is the most powerful force in the universe.", "Albert Einstein"],
    ["Computers are like Old Testament gods: lots of rules and no mercy.", "Joseph Campbell"],
    ["Conflict is the spice of life.", "Idiom"],
    ["Courage is a mean with regard to fear and confidence.", "Aristotle"],
    ["Cowards die many times before their deaths.<br>The valiant never taste of death but once.<br>Of all the wonders that I yet have heard,<br>It seems to me most strange that men should fear,<br>Seeing that death, a necessary end,<br>Will come when it will come.", "Caesar, Julius Caesar"],
    ["Critical thinking is a desire to seek, patience to doubt, fondness to meditate, slowness to assert, readiness to consider, carefulness to dispose and set in order; and hatred for every kind of imposture.", "Francis Bacon"],
    ["Crom, I have never prayed to you before. I have no tongue for it. No one, not even you, will remember if we were good men or bad. Why we fought, or why we died. All that matters is that two stood against many. That's what's important! Valor pleases you, Crom...so grant me one request. Grant me revenge! And if you do not listen, then the Hell with you!", "Conan, Conan the Barbarian"],
    ["Cry in the dojo. Laugh on the battlefield.", "Japanese Proverb"],
    ["Cry ‘Havoc!’, and let slip the dogs of war.", "Mark Antony, Julius Caesar"],
    ["Curious is the trap-maker's art...his efficacy unwitnessed by his own eyes.", "The Narrator, Darkest Dungeon"],
    ["Damnant quod non intelligunt (They condemn what they do not understand).", "Marcus Tullius Cicero"],
    ["Dark humor is like food, not everyone gets it.", "Unknown"],
    ["Dark times lie ahead of us and there will be a time when we must choose between what is easy and what is right.", "Albus Dumbledore, Harry Potter and the Goblet of Fire"],
    ["Davos Seaworth: It seems to me that most men are grey.<br>Melisandre: If half of an onion is black with rot, it is a rotten onion. A man is good, or he is evil.", "A Clash of Kings"],
    ["Dead rats don't squeak.", "Sandor Clegane, Game of Thrones"],
    ["Death is a preferable alternative to communism.", "Liberty Prime, Fallout 3"],
    ["Death is lighter than a feather, duty heavier than a mountain.", "Rand al'Thor, The Great Hunt"],
    ["Death whispers into my ear, ‘live now, for I am coming.’", "Virgil"],
    ["Democracy is two wolves and a lamb voting on what to have for lunch. Liberty is a well-armed lamb contesting the vote.", "Unknown"],
    ["Desperate times call for desperate measures.", "Idiom"],
    ["Discretion is the better part of valor.", "Proverb"],
    ["Do not go gentle into that good night.", "Dylan Thomas"],
    ["Do not rest on your laurels.", "Greek Idiom"],
    ["Do or do not, there is no try.", "Yoda, The Empire Strikes Back"],
    ["Do to others what you want them to do to you. This is the meaning of the law of Moses and the teaching of the prophets.", "Matthew 7:12"],
    ["Do what you can, with what you have, where you are.", "Theodore Roosevelt"],
    ["Do you not know death when you see it, old man?! This is my hour!", "The Witch-King of Angmar, The Lord of the Rings: The Return of the King"],
    ["Do you not know, my son, with what little understanding the world is ruled?", "Pope Julius III"],
    ["Doing the right thing never requires any subterfuge. It is always simple and direct.", "Calvin Coolidge"],
    ["Don't be in a hurry to condemn because he doesn't do what you do or think as you think or as fast. There was a time when you didn't know what you know today.", "Malcolm X"],
    ["Don't ever take a fence down until you know the reason it was put up.", "G. K. Chesterton"],
    ["Don't fight a battle if you don't gain anything by winning.", "Erwin Rommel"],
    ["Don't give up the ship.", "James Lawrence"],
    ["Don't hit at all if it is honorably possible to avoid hitting; but never hit softly.", "Theodore Roosevelt"],
    ["Don't lose your way.", "Proverb"],
    ["Don't tease the octopus, kids!", "Ultros, Final Fantasy VI"],
    ["Don't tread on me.", "Motto on the Gadsden Flag"],
    ["Don't underestimate the hole your absence would leave.", "Jordan B. Peterson"],
    ["Eccentricity is one of the hallmarks of strong characters and original minds.", "Andrew Garve"],
    ["Eddard Stark: What you suggest is treason.<br>Petyr Baelish: Only if we lose.", "Game of Thrones"],
    ["Education is the best provision for old age.", "Aristotle"],
    ["Enter not into the path of the wicked, and go not in the way of evil men.", "Proverbs 4:14"],
    ["Et tu, Brute? (You as well, Brutus?)", "Julius Caesar to Marcus Junius Brutus, Julius Caesar"],
    ["Even a fool, when he holdeth his peace, is counted wise: and he that shutteth his lips is esteemed a man of understanding.", "Proverbs 17:28"],
    ["Even a stopped clock is right twice a day.", "Proverb"],
    ["Even a stray has pride. Here I pay my debt.", "Gabranth, Final Fantasy XII"],
    ["Even brute beasts and wandering birds do not fall for the same traps or nets twice.", "Saint Jerome"],
    ["Even if I knew that tomorrow the world would go to pieces, I would still plant my apple tree.", "Martin Luther"],
    ["Even the lion has to defend himself against flies.", "German Proverb"],
    ["Every French soldier carries a marshal's baton in his knapsack.", "Napoleon Bonaparte"],
    ["Every decision you make can change the world. The best life is the one the gods don't notice. You want to live free, boy, live quietly.", "Whiskeyjack, Gardens of the Moon"],
    ["Every genuine work of art has as much reason for being as the earth and the sun.", "Ralph Waldo Emerson"],
    ["Every great advance in science has issued from a new audacity of imagination.", "John Dewey"],
    ["Every man has a price he will willingly accept, even for what he hoped never to sell.", "Cutler Beckett, Pirates of the Caribbean: Dead Man's Chest"],
    ["Every normal man must be tempted, at times, to spit on his hands, hoist the black flag, and begin slitting throats.", "H. L. Mencken"],
    ["Everyone creates the thing they dread. Men of peace create engines of war, invaders create avengers.", "Ultron, Avengers: Age of Ultron"],
    ["Everything in space obeys the laws of physics. If you know these laws, and obey them, space will treat you kindly. And don't tell me that man doesn't belong out there. Man belongs wherever he wants to go - and he'll do plenty well when he gets there.", "Wernher von Braun"],
    ["Everything should be made as simple as possible, but not simpler.", "Albert Einstein"],
    ["Extremism in the defense of liberty is no vice. And let me remind you also that moderation in the pursuit of justice is no virtue.", "Barry Goldwater"],
    ["Facilis descensus Averno (The descent to hell is easy).", "Virgil, The Aeneid"],
    ["Familiarity breeds contempt.", "Proverb"],
    ["Fear cuts deeper than swords.", "Arya Stark, A Game of Thrones"],
    ["Fear is the mind-killer.", "Litany of Fear, Dune"],
    ["Few weapons are as effective as terror.", "Roose Bolton, House Bolton (Histories & Lore)"],
    ["Fiat justitia ruat caelum (Let justice be done though the heavens fall).", "Latin Proverb"],
    ["For iron by itself can draw a man to use it.", "Odysseus, The Odyssey"],
    ["For once a thing is known, it can never be unknown. It can only be forgotten.", "Anita Brookner"],
    ["For the greater good.", "Idiom"],
    ["Freedom would not be so difficult to attain were prison not so sweet.", "Diogenes"],
    ["From everyone who has been given much, much will be demanded; and from the one who has been entrusted with much, much more will be asked.", "Luke 12:48"],
    ["Get your facts first, then you can distort them as you please.", "Mark Twain"],
    ["Give a man a mask and he will show his true face.", "Oscar Wilde"],
    ["Give assistance, not advice, in a crisis.", "Aesop"],
    ["Give me liberty, or give me death!", "Patrick Henry"],
    ["God created men, Col. Colt made them equal.", "American Adage"],
    ["God gives the nuts, but he does not crack them.", "Franz Kafka"],
    ["God smiles on results.", "Mamun, Last Argument of Kings"],
    ["Godless? Why, Aeron, I am the godliest man ever to raise sail! You serve one god, Damphair, but I have served ten thousand. From Ib to Asshai, when men see my sails, they pray.", "Euron Greyjoy, A Feast for Crows"],
    ["Government, even in its best state, is but a necessary evil; in its worst state, an intolerable one.", "Thomas Paine"],
    ["Great is the weapon that cuts on its own.", "The Narrator, Darkest Dungeon"],
    ["Happiness: a good bank account, a good cook and a good digestion.", "Jean Jacques Rousseau"],
    ["Have the courage to think and act on your own. And have the courage to disobey.", "Sage Yulyana, Bravely Default"],
    ["Have you gone soft Clegane? I always thought you had a talent for violence. Burn the villages, burn the farms. Let them know what it means to choose the wrong side.", "Tywin Lannister to Gregor Clegane, Game of Thrones"],
    ["He picked up the lemons that Fate had sent him and started a lemonade-stand.", "Elbert Hubbard on Marshall Pinckney Wilder"],
    ["He that always gives way to others will end in having no principles of his own.", "Aesop"],
    ["He that would make his own liberty secure, must guard even his enemy from oppression; for if he violates this duty, he establishes a precedent that will reach to himself.", "Thomas Paine"],
    ["He was...a painter. A painter who only used red.", "Jaime Lannister on Barristan Selmy, Game of Thrones"],
    ["He who conquers others is strong; He who conquers himself is mighty.", "Laozi"],
    ["He who destroys a good book kills reason itself.", "John Milton"],
    ["He who has lost honor can lose nothing more.", "Publilius Syrus"],
    ["He who knows others is wise; He who knows himself is enlightened.", "Laozi"],
    ["He who strikes first, strikes twice.", "Proverb"],
    ["He who wishes to be obeyed must know how to command.", "Niccolo Machiavelli"],
    ["Heav'n has no rage, like love to hatred turn'd<br>Nor hell a fury, like a woman scorn'd.", "Zara, The Mourning Bride"],
    ["Her lips said no, but her eyes said read my lips.", "Niles Crane, Frasier"],
    ["History is a set of lies agreed upon.", "Napoleon Bonaparte"],
    ["History is written by the victors.", "Unknown"],
    ["Honesty is the best policy; I will stick to that. The good shall have my hand and heart; but the bad neither foot nor friendship.", "Sancho Panza, Don Quixote"],
    ["Honor is simply the morality of superior men.", "H. L. Mencken"],
    ["Honour, eh? What the hell is that anyway? Every man thinks it's something different. You can't drink it. You can't fuck it. The more of it you have the less good it does you, and if you've got none at all you don't miss it.", "Nicomo Cosca, Before They Are Hanged"],
    ["Hope for the best, prepare for the worst.", "Idiom"],
    ["Hope is the first step on the road to disappointment.", "Librarian, Dawn of War"],
    ["Humor is a rubber sword - it allows you to make a point without drawing blood.", "Mary Hirsch"],
    ["I against my brother. I and my brother against my cousin. I, my brother, and my cousin against the world.", "Bedouin Proverb"],
    ["I always thought there was at least one person in the stands who had never seen me play, and I didn't want to let him down.", "Joe DiMaggio"],
    ["I am an Anarchist. All good men are Anarchists. All cultured, kindly men; all gentlemen; all just men are Anarchists. Jesus was an Anarchist.", "Elbert Hubbard"],
    ["I am not afraid of an army of lions led by a sheep; I am afraid of an army of sheep led by a lion.", "Alexander the Great"],
    ["I consider it completely unimportant who in the party will vote, or how; but what is extraordinarily important is this - who will count the votes, and how.", "Joseph Stalin"],
    ["I dare do all that may become a man; Who dares do more is none.", "Macbeth, Macbeth"],
    ["I disapprove of what you say, but I will defend to the death your right to say it.", "Voltaire"],
    ["I don't trust a man who talks about ethics when he is picking my pocket. But if he is acting in his own self-interest and says so, I have usually been able to work out some way to do business with him.", "Robert A. Heinlein"],
    ["I fear all we have done is to awaken a sleeping giant and fill him with a terrible resolve.", "Isoroku Yamamoto, Tora! Tora! Tora!"],
    ["I fear not the man who has practiced 10,000 kicks once, but I fear the man who has practiced one kick 10,000 times.", "Bruce Lee"],
    ["I find the great thing in this world is not so much where we stand, as in what direction we are moving.", "Oliver Wendell Holmes"],
    ["I hate to be a kicker,<br>I always long for peace,<br>But the wheel that squeaks the loudest,<br>Is the one that gets the grease.", "Josh Billings"],
    ["I have learned all kinds of things from my many mistakes. The one thing I never learn is to stop making them.", "Joe Abercrombie, Last Argument of Kings"],
    ["I have not yet begun to fight!", "John Paul Jones"],
    ["I knew a man who once said ‘Death smiles at us all. All a man can do is smile back.’", "Maximus Decimus Meridius, Gladiator"],
    ["I like a simple world where common things are done in common ways. I suppose you could say I'm a man of the people.", "Shogo Makishima"],
    ["I live and love in God's peculiar light.", "Michaelangelo Buonarroti"],
    ["I must confess I have always had some sympathy with villains. Heroism makes fine entertainment, but sooner or later someone has to get things done.", "Bayaz, The Trouble with Peace"],
    ["I never asked for this crown. Gold is cold and heavy on the head, but so long as I am the king, I have a duty...If I must sacrifice one child to the flames to save a million from the dark...Sacrifice...is never easy, Davos. Or it is no true sacrifice.", "Stannis Baratheon, A Storm of Swords"],
    ["I never think of the future, it comes soon enough.", "Albert Einstein"],
    ["I pray, Mr Adams, that the United States does not suffer unduly from its want of a Monarchy.", "King George III to John Adams"],
    ["I rose too high, loved too hard, dared too much. I tried to grasp a star, overreached, and fell.", "Jon Connington, A Dance with Dragons"],
    ["I saw the angel in the marble and carved until I set him free.", "Michelangelo"],
    ["I saw the crown of France laying on the ground, so I picked it up with my sword.", "Napoleon Bonaparte"],
    ["I suppose it is tempting, if the only tool you have is a hammer, to treat everything as if it were a nail.", "Abraham Maslow"],
    ["I swear to you, I was never so alive as when I was winning this throne, or so dead as now that I've won it.", "Robert Baratheon, A Game of Thrones"],
    ["I think the only time people really have value is when they act according to their own will.", "Shogo Makishima"],
    ["I was always willing to be reasonable until I had to be unreasonable. Sometimes reasonable men must do unreasonable things.", "Marvin Heemeyer"],
    ["I will marshall all the media forces of darkness to hound you to an assisted suicide.", "Malcolm Tucker, In the Loop"],
    ["I will not accept if nominated and will not serve if elected.", "William Tecumseh Sherman"],
    ["I will not trade one dictatorship for another.", "Graccus, Gladiator"],
    ["I will reveal to you a love potion, without medicine, without herbs, without any witch's magic; if you want to be loved, then love.", "Hecaton of Rhodes"],
    ["I wish to have no connection with any ship that does not sail fast; for I intend to go in harm's way.", "John Paul Jones"],
    ["I wish you good fortune in the wars to come.", "Mance Rayder, Game of Thrones"],
    ["I'd rather be lucky than good.", "Lefty Gomez"],
    ["I'll never be frightened of shepherds. It's the sheep who trouble me.", "Petyr Baelish, A Clash of Kings"],
    ["I'm a coward. A coward who cannot even defy orders he knows he ought not follow.", "Cecil Harvey, Final Fantasy IV"],
    ["I, like God, do not play with dice and do not believe in coincidence.", "V, V for Vendetta"],
    ["If I had my choice I would kill every reporter in the world, but I am sure we would be getting reports from Hell before breakfast.", "William Tecumseh Sherman"],
    ["If I have seen further it is by standing on the shoulders of Giants.", "Isaac Newton"],
    ["If a man says he is not afraid of dying, he is either lying or is a gurkha.", "Sam Manekshaw"],
    ["If an injury has to be done to a man it should be so severe that his vengeance need not be feared.", "Niccolo Machiavelli"],
    ["If any man's money can be taken by a so-called government, without his own personal consent, all his other rights are taken with it; for with his money the government can, and will, hire soldiers to stand over him, compel him to submit to its arbitrary will, and kill him if he resists.", "Lysander Spooner"],
    ["If it ain't broke, don't fix it.", "Bert Lance"],
    ["If it is not right do not do it; if it is not true do not say it.", "Marcus Aurelius"],
    ["If it's stupid but works, it isn't stupid.", "Murphy's War Laws"],
    ["If man is moderated and contented, then even age is no burden; if he is not, then even youth is full of cares.", "Plato"],
    ["If one wishes not to be handled, one should not grow a handle.", "Jiu Jitsu Proverb"],
    ["If people can't control their own emotions, then they have to start trying to control other people's behavior.", "John Cleese"],
    ["If someone stands in the way of true justice, you just walk up behind him, and stab him in the heart.", "Ra's al Ghul, Batman Begins"],
    ["If the brain were so simple we could understand it, we would be so simple we couldn't.", "Lyall Watson"], 
    ["If there arose to-morrow a band of fanatics advocating cannibalism that was as daring in political enterprise and as skilful in rounding up morons as the Anti-Saloon league was in 1919, two Congressmen out of three would be converted to its gospel instantly, and three public-school teachers out of four would probably be serving it as evangelists within a month.", "H. L. Mencken"],
    ["If there must be trouble, let it be in my day, that my child may have peace.", "Thomas Paine"],
    ["If they stand behind you, give them protection. If the stand beside you, give them respect. If they stand against you, show them no mercy.", "Unknown"],
    ["If this fall into thy hand, revolve. In my stars I am above thee, but be not afraid of greatness. Some are born great, some achieve greatness, and some have greatness thrust upon 'em.", "Malvolio, Twelfth Night"],
    ["If we can stop him, we shall prevent the collapse of Western civilization...No pressure.", "Sherlock Holmes, Sherlock Holmes: A Game of Shadows"],
    ["If we fight for money, I'll stop hitting you when you ask me to. If we fight for honor, I'll stop hitting you when I feel like it.", "Rickson Gracie"],
    ["If ye love wealth better than liberty, the tranquility of servitude better than the animating contest of freedom, go home from us in peace. We ask not your counsels or arms. Crouch down and lick the hands which feed you. May your chains set lightly upon you, and may posterity forget that ye were our countrymen.", "Samuel Adams"],
    ["If ye were of the world, the world would love his own: but because ye are not of the world, but I have chosen you out of the world, therefore the world hateth you.", "John 15:19"],
    ["If you can question it, it's science. If you can't, it's propaganda.", "Unknown"],
    ["If you cannot be a poet, be the poem.", "David Carradine"],
    ["If you find yourself in a hole, stop digging.", "Adage"],
    ["If you owe a bank enough money you own it.", "Unknown, A New Dictionary of Quotations on Historical Principles from Ancient and Modern Sources"],
    ["If you pick up a starving dog and make him prosperous, he will not bite you. This is the principal difference between a dog and a man.", "Mark Twain"],
    ["If you start at the top of the ladder, there's only one way to go.", "Christopher Lee"],
    ["If you want to change the world, pick up your pen and write.", "Martin Luther"],
    ["If you're going through hell, keep going.", "Winston Churchill"],
    ["If you're the first out of the door, that's not called panicking.", "John Tuld, Margin Call"],
    ["If your advance is going well, you are walking into an ambush.", "Murphy's War Laws"],
    ["In America the President reigns for four years, and Journalism governs for ever and ever. Fortunately, in America journalism has carried its authority to the grossest and most brutal extreme. As a natural consequence it has begun to create a spirit of revolt. People are amused by it, or disgusted by it, according to their temperaments. But it is no longer the real force it was. It is not seriously treated.", "Oscar Wilde"],
    ["In avoiding one evil, care must be taken not to fall into another.", "Aesop"],
    ["In debates between anarchists and statists, the burden of proof clearly should rest on those who place their trust in the state. Anarchy's mayhem is wholly conjectural; the state's mayhem is undeniably, factually horrendous.", "Robert Higgs"],
    ["In nothing do men more nearly approach the gods than in giving health to men.", "Marcus Tullius Cicero"],
    ["In preparing for battle I have always found that plans are useless, but planning is indispensable.", "Dwight Eisenhower"],
    ["In sterquiliniis invenitur (in filth it shall be found).", "Carl Jung"],
    ["In the absence of light, darkness prevails.", "Trevor Bruttenholm, Hellboy"],
    ["In the game of thrones, even the humblest pieces can have wills of their own. Sometimes they refuse to make the moves you've planned for them.", "Petyr Baelish, A Feast for Crows"],
    ["In the land of the blind, the one-eyed man is king.", "Desiderius Erasmus"],
    ["In the sweat of thy face shalt thou eat bread, till thou return unto the ground; for out of it wast thou taken: for dust thou art, and unto dust shalt thou return.", "Genesis 3:19"],
    ["In wartime, truth is so precious that she should always be attended by a bodyguard of lies.", "Winston Churchill"],
    ["Instrumental or mechanical science is the noblest and, above all others, the most useful.", "Leonardo da Vinci"],
    ["Iron sharpeneth iron; so a man sharpeneth the countenance of his friend.", "Proverbs 27:17"],
    ["Is there anything more worthless than excuses?", "Kellanved, Dust of Dreams"],
    ["It all goes back and back, to our mothers and fathers and theirs before them. We are puppets dancing on the strings of those who came before us, and one day our own children will take up our strings and dance in our steads.", "Tyrion Lannister"],
    ["It could be that the purpose of your life is only to serve as a warning to others.", "Ashleigh Brilliant"],
    ["It does not take a majority to prevail, but rather an irate, tireless minority, keen on setting brushfires of freedom in the minds of men.", "Samuel Adams"],
    ["It has been said that politics is the second oldest profession. I have learned that it bears a striking resemblance to the first.", "Ronald Reagan"],
    ["It has been said, ‘time heals all wounds.’ I do not agree. The wounds remain. In time, the mind, protecting its sanity, covers them with scar tissue and the pain lessens. But it is never gone.", "Rose Fitzgerald Kennedy"],
    ["It is a newspaper's duty to print the news and raise hell.", "Wilbur F. Storey"],
    ["It is better to be feared than loved, if you cannot be both.", "Niccolo Machiavelli"],
    ["It is difficult to get a man to understand something, when his salary depends on his not understanding it.", "Upton Sinclair"],
    ["It is easy to be brave at a safe distance.", "Aesop"],
    ["It is hard to fill a cup that is already full.", "Mo'at, Avatar"],
    ["It is no good hammering your sword into a plowshare if you must forge it again on the morrow.", "Brynden Tully, A Game of Thrones"],
    ["It is not light that we need, but fire; it is not the gentle shower, but thunder. We need the storm, the whirlwind, and the earthquake.", "Frederick Douglass"],
    ["It is not my sword, Mondego, but your past that disarmed you.", "Edmond Dantes, The Count of Monte Cristo"],
    ["It is the job of thinking people not to be on the side of the executioners.", "Albert Camus"],
    ["It is the mark of an educated mind to rest satisfied with the degree of precision which the nature of the subject admits and not to seek exactness where only an approximation is possible.", "Aristotle"],
    ["It is well that war is so terrible, otherwise we should grow too fond of it.", "Robert E. Lee to James Longstreet"],
    ["It isn't necessary to imagine the world ending in fire or ice. There are two other possibilities: one is paperwork, and the other is nostalgia.", "Frank Zappa"],
    ["It takes a great deal of bravery to stand up to our enemies, but just as much to stand up to our friends.", "Albus Dumbledore, Harry Potter and the Philosopher's Stone"],
    ["It's a bad carpenter that blames his hammer.", "Proverb"],
    ["It's a big club and you ain't in it.", "George Carlin"],
    ["It's a strange thing, the first time you cut a man. You realize we're nothing but sacks of meat and blood, and some bone to keep it all standing.", "Jaime Lannister, Game of Thrones"],
    ["It's better to die on your feet than to live on your knees.", "Emiliano Zapata"],
    ["It's easy to see the errors of others, but hard to see your own.", "Dhammapada 28:252"],
    ["It's not the net result of one's life that's important! It's the day-to-day concerns, the personal victories, and the celebration of life... and love! It's enough if people are able to experience the joy that each day can bring!", "Terra Branford, Final Fantasy VI"],
    ["It's our wits that make us men.", "Malcolm Wallace, Braveheart"],
    ["It's tempting to see your enemies as evil, all of them, but there's good and evil on both sides in every war ever fought.", "Jorah Mormont, Game of Thrones"],
    ["Journalism is printing what others don't want printed, all the rest is public relations.", "George Orwell"],
    ["Judge not according to the appearance, but judge righteous judgment.", "John 7:24"],
    ["Just Do It.", "Shia LaBeouf"],
    ["Just because you're paranoid doesn't mean they aren't after you.", "Captain John Yossarian, Catch-22"],
    ["Justice is subject to dispute; might is easily recognized and not disputed. So we cannot give might to justice.", "Blaise Pascal"],
    ["Justice. I remember justice. It had a pleasant taste. Justice was what we were about when Beric led us, or so we told ourselves. We were king's men, knights, and heroes...but some knights are dark and full of terrors, my lady. War makes monsters of us all.", "Thoros of Myr, A Feast for Crows"],
    ["Keep your friends close and your enemies closer.", "Proverb"],
    ["Kill the boy, Jon Snow. Winter is almost upon us. Kill the boy and let the man be born.", "Aemon Targaryen, A Dance with Dragons"],
    ["King Jaehaerys once told me that madness and greatness are two sides of the same coin. every time a new Targaryen is born, he said, the gods toss the coin in the air, and the world holds its breath to see how it will land.", "Barristan Selmy, A Storm f fSwords"],
    ["Kings have no friends, only subjects and enemies.", "Stannis Baratheon, A Clash of Kings"],
    ["Know your enemy and know yourself and you can fight a hundred battles without disaster.", "Sun Tzu"],
    ["Knowledge is power, hide it well.", "Librarian, Dawn of War"],
    ["Knowledge itself is power.", "Francis Bacon"],
    ["Learn to obey before you command.", "Solon"],
    ["Learning without thinking is wasted effort; thinking without learning is dangerous.", "Confucius"],
    ["Lessons not learned in blood are soon forgotten.", "Clyde Shelton, Law Abiding Citizen"], 
    ["Let no emperor be subject to anyone but God and justice.", "Frederick I"],
    ["Let the games begin!", "Greek Proverb"],
    ["Let those who consider themselves my enemies reveal their hands.", "Jordan B. Peterson"],
    ["Liberty is not the daughter, but the mother of order.", "Pierre-Joseph Proudhon"],
    ["Libraries are as the shrine where all the relics of the ancient saints, full of true virtue, and all that without delusion or imposture are preserved and restored.", "Francis Bacon"],
    ["Life is not a song, sweetling. Someday you may learn that, to your sorrow.", "Petyr Baelish to Sansa Stark, A Game of Thrones"],
    ["Life is too important to be taken seriously.", "Oscar Wilde"],
    ["Life's a garden, dig it.", "Joe Dirt, Joe Dirt"],
    ["Life...Dreams...Hope...Where do they come from? And where do they go...? Such meaningless things...I'll destroy them all!", "Kefka Palazzo, Final Fantasy VI"],
    ["Live free or die: Death is not the worst of evils.", "John Stark"],
    ["Lord Seaworth is a man of humble birth, but he reminded me of my duty, when all I could think of was my rights. I had the cart before the horse, Davos said. I was trying to win the throne to save the kingdom, when I should have been trying to save the kingdom to win the throne.", "Stannis Baratheon, A Storm of Swords"],
    ["Loyal service means telling hard truths.", "Davos Seaworth, Game of Thrones"],
    ["Madness and genius are two sides to the same coin.", "John Hendy"],
    ["Make your friends rich and your enemies rich and wait to find out which is which.", "Ultron, Avengers: Age of Ultron"],
    ["Man has but three events in his life: to be born, to live, and to die. He is not conscious of his birth, he suffers at his death and he forgets to live.", "Jean de la Bruyere"],
    ["Manners maketh man.", "William Horman"],
    ["Many hands make light work.", "Proverb"],
    ["Many that live deserve death. And some that die deserve life. Can you give it to them? Then do not be too eager to deal out death in judgement.", "Gandalf, The Fellowship of the Ring"],
    ["Mathematics is the gate and key to the sciences.", "Roger Bacon"],
    ["Measure what is measurable, and make measurable what is not so.", "Galileo Galilei"],
    ["Men are like linoleum floors. Lay 'em right and you can walk all over them for years.", "Mae West"],
    ["Men are moved by two levers only: fear and self interest.", "Napoleon Bonaparte"],
    ["Men in their arrogance claim to understand the nature of creation, and devise elaborate theories to describe its behavior. But always they discover in the end that God was quite a bit more clever than they thought.", "Miriam Godwinson"],
    ["Men of honor will do things for their children that they would never consider doing for themselves.", "Petyr Baelish, A Feast for Crows"],
    ["Men test ideas and women test men.", "Jordan B. Peterson"],
    ["Misogynist: A man who hates women as much as women hate one another.", "H. L. Mencken"],
    ["More men worship the rising than the setting sun.", "Gnaeus Pompeius Magnus"],
    ["Most people respect the badge, everyone respects the gun.", "Tom Cowan, Righteous Kill"],
    ["My father was fond of saying you need three things in life - a good doctor, a forgiving priest, and a clever accountant.", "Oskar Schindler, Schindler's List"],
    ["My favourite definition of an intellectual: ‘Someone who has been educated beyond his/her intelligence.’", "Arthur C. Clarke"],
    ["My hands are stained with blood. I see little reason to stay them now.", "Vayne Solidor, Final Fantasy XII"],
    ["My mind is my weapon. My brother has his sword, King Robert has his warhammer, and I have my mind...and a mind needs books as a sword needs a whetstone, if it is to keep its edge.", "Tyrion Lannister, A Game of Thrones"],
    ["My wants do not matter. It may be that the Many-Faced God has led you here to be his instrument, but when I look at you I see a child...and worse a girl child. Many have served Him of Many Faces through the centuries, but only a few of His servants have been women. Women bring life into the world. We bring the gift of death. No one can do both.", "The Kindly Man, A Feast for Crows"],
    ["Nay, alone I am a weak creature, having no strength or might in me; yet in times past hath God made me a great vessel of wrath and a sword of deliverance. And I trust, shall do so again.", "Solomon Kane, The Moon of Skulls"],
    ["Never engage into a contract where one party is incentivised to break it.", "Unknown"],
    ["Never forget what you are, for surely the world will not. Make it your strength. Then it can never be your weakness. Armor yourself in it, and it will never be used to hurt you.", "Tyrion Lannister, A Game of Thrones"],
    ["Never interrupt your enemy when he is making a mistake.", "Napoleon Bonaparte"],
    ["Never slap a man who's chewing tobacco.", "Idiom"],
    ["Never trust the advice of a man in difficulties.", "Aesop"],
    ["Never was anything great achieved without danger.", "Niccolo Machiavelli"],
    ["Nil desperandum, -- Never Despair. That is a motto for you and me. All are not dead; and where there is a spark of patriotic fire, we will rekindle it.", "Samuel Adams"],
    ["No act of kindness, no matter how small, is ever wasted.", "Aesop"],
    ["No man but a blockhead ever wrote, except for money.", "Samuel Johnson"],
    ["No man is born into the world whose work Is not born with him. There is always work, And tools to work withal, for those who will; And blessed are the horny hands of toil.", "James Russell Lowell"],
    ["No man is free. Only children and fools think elsewise.", "Tywin Lannister, A Dance with Dragons"],
    ["No man's life, liberty or property are safe while the Legislature is in session.", "Gideon Tucker"],
    ["No one escapes their past. No one escapes Judgement.", "Lewis Prothero, V for Vendetta"],
    ["No plan of operations extends with any certainty beyond the first contact with the main hostile force.", "Helmuth von Moltke the Elder"],
    ["No retreat, no surrender. That is Spartan law. And by Spartan law, we will stand and fight...and die. A new age has begun: an age of freedom! And all will know that 300 Spartans gave their last breath to defend it!", "Leonidas, 300"],
    ["No tree, it is said, can grow to heaven unless its roots reach down to hell.", "Carl Jung"],
    ["No weapon that is formed against thee shall prosper; and every tongue that shall rise against thee in judgment thou shalt condemn. This is the heritage of the servants of the LORD, and their righteousness is of me, saith the LORD.", "Isaiah 54:17"],
    ["No-one is equal to anything. Even the same man is not equal to himself on different days.", "Thomas Sowell"],
    ["Norrington: One good deed is not enough to redeem a man of a lifetime of wickedness.<br>Jack Sparrow: Though it seems enough to condemn him.", "Pirates of the Carribean"],
    ["Not only can the camera lie. The camera always lies.", "Malcolm Muggeridge"],
    ["Not that I speak in respect of want: for I have learned, in whatsoever state I am, therewith to be content.", "Philippians 4:11"],
    ["Nothing in this world can take the place of persistence. Talent will not: nothing is more common than unsuccessful men with talent. Genius will not; unrewarded genius is almost a proverb. Education will not: the world is full of educated derelicts. Persistence and determination alone are omnipotent. The slogan Press On! has solved and always will solve the problems of the human race.", "Calvin Coolidge"],
    ["Nothing is particularly hard if you divide it into small jobs.", "Henry Ford"],
    ["Nothing is so permanent as a temporary government program.", "Milton Friedman"],
    ["Nothing's over while I'm breathing!", "Quaritch, Avatar"],
    ["Now I am become Death, the destroyer of worlds.", "Vishnu, Bhagavad Gita"],
    ["Numberless are the world's wonders, but none more wonderful than man.", "Sophocles"],
    ["Of all men's miseries the bitterest is this: to know so much and to have control over nothing.", "Herodotus"],
    ["Of all tyrannies, a tyranny sincerely exercised for the good of its victims may be the most oppressive. It would be better to live under robber barons than under omnipotent moral busybodies. The robber baron's cruelty may sometimes sleep, his cupidity may at some point be satiated; but those who torment us for our own good will torment us without end for they do so with the approval of their own conscience.", "C. S. Lewis"],
    ["Of old the expert in battle would first make himself invincible and then wait for his enemy to expose his vulnerability.", "Sun Tzu"],
    ["Oh what a tangled web we weave<br>When first we practice to deceive.", "Walter Scott"],
    ["Oh, It's truth you want? Be careful, my lady. Tyrion says that people often claim to hunger for the truth, but seldom like the taste when it's served up.", "Jaime Lannister, A Clash of Kings"],
    ["On whose shoulders better to stand than those of the would-be gods!", "Dr. Cid, Final Fantasy XII"],
    ["Once more unto the breach, dear friends, once more.", "King Henry V, Henry V"],
    ["Once you eliminate the impossible, whatever remains, no matter how improbable, must be the truth.", "Sherlock Holmes, The Sign of the Four"],
    ["Once you've got a task to do, it's better to do it than live with the fear of it.", "Logen Ninefingers, The Blade Itself"],
    ["One good turn deserves another.", "Aesop"],
    ["One must not tie a ship to a single anchor, nor life to a single hope.", "Epictetus"],
    ["One scabbed sheep mars the whole flock.", "Proverb"],
    ["Only a fool fights a battle he knows he cannot win.", "Genghis Khan"],
    ["Only a fool learns from his own mistakes. The wise man learns from the mistakes of others.", "Otto von Bismarck"],
    ["Only a warrior chooses pacifism; others are condemned to it.", "Eduardo Garcia"],
    ["Only death pays for life.", "Mirri Maz Duur, A Game of Thrones"],
    ["Only in death does duty end.", "Warhammer 40,000: 3rd Edition"],
    ["Only the dead can know peace from this evil.", "Anonymous, 4Chan"],
    ["Only the dead have seen the end of war.", "George Santayana"],
    ["Our Father, we yearn for a better understanding of spiritual things, that we may know surely what Thy will is for us and for our Nation. Give to us clear vision that we may know where to stand and what to stand for - because unless we stand for something, we shall fall for anything.", "Chaplain Peter Marshall"],
    ["Our destiny is frequently met in the very paths we take to avoid it.", "Jean de La Fontaine"],
    ["Our job is to report the news, not fabricate it. That's the government's job.", "Dascombe, V for Vendetta"],
    ["Our scientific power has outrun our spiritual power. We have guided missiles and misguided men.", "Martin Luther King, Jr."],
    ["Out of chaos God made a world, and out of high passions comes a people.", "Lord Byron"],
    ["Overconfidence is the greatest enemy!", "Yoshimitsu, Soul Calibur II"],
    ["Pain is temporary, glory is eternal.", "Proverb"],
    ["Pale Death beats equally at the poor man's gate and at the palaces of kings.", "Horace"],
    ["People aren't against you; they are for themselves.", "Unknown"],
    ["People don't have ideas. Ideas have people.", "Carl Jung"],
    ["People should not be afraid of their governments, governments should be afraid of their people.", "V, V for Vendetta"],
    ["People tend to take pride in who they are. And that's a bad idea, because that stops you from becoming who you could be. Because, if you're proud of who you are, you won't let that go when it's necessary.", "Jordan B. Peterson"],
    ["Perfection is achieved, not when there is nothing more to add, but when there is nothing left to take away.", "Antoine de Saint-Exupery"],
    ["Physical books are more than the words they contain. They're also tools to stimulate your senses and adjust your thinking.", "Shogo Makishima"],
    ["Please all, and you will please none.", "Aesop"],
    ["Politics have no relation to morals.", "Niccolo Machiavelli"],
    ["Politics is downstream of culture.", "Andrew Breitbart"],
    ["Politics makes strange bedfellows.", "Proverb"],
    ["Politics: the art of using euphemisms, lies, emotionalism and fear-mongering to dupe average people into accepting, or even demanding, their own enslavement.", "Larken Rose"],
    ["Power resides where men believe it resides, it's a trick, a shadow on the wall. And a very small man can cast a very large shadow.", "Varys, A Clash of Kings"],
    ["Put your money where your mouth is.", "Idiom"],
    ["Quis custodiet ipsos custodes (Who will guard the guards themselves)?", "Juvenal"],
    ["Remember, democracy never lasts long. It soon wastes, exhausts, and murders itself. There never was a democracy yet that did not commit suicide.", "John Adams"],
    ["Remember, no human condition is ever permanent: then you will not be overjoyed in good fortune, not too sorrowful in misfortune.", "Socrates"],
    ["Respect is earned not given.", "Proverb"],
    ["Revenge is a dish that should be eaten cold.", "Charles Maurice de Talleyrand-Perigord"],
    ["Right action is better than knowledge; but in order to do what is right, we must know what is right.", "Charlemagne"],
    ["Rome wasn't built in a day.", "Proverb"],
    ["Rudd Threetrees was a stubborn bastard, and Bethod a sly bastard, and the Bloody-Nine an evil bastard, the dead know that, but there are times I miss 'em. Those were men! They said a thing, they did a fucking thing!", "Black Dow, The Heroes"],
    ["Rules are for children. This is war, and in war the only crime is to lose.", "Bayaz, Last Argument of Kings"],
    ["Save your pity and your mercy; I have no use for it.", "Saruman, The Return of the King"],
    ["Science, all by itself, has no moral dimension. The same poison-containing drug which cures when taken in small doses, may kill when taken in excess.", "Wernher von Braun"],
    ["Seek not the lie of the immortals, but enjoy to the full the resources that are within reach.", "Pindar"],
    ["Shall the clay say to him that fashioneth it, What makest thou? or thy work, He hath no hands?", "Isaiah 45:9"],
    ["Show me the man and I'll show you the crime.", "Lavrentiy Beria"],
    ["Si vis pacem, para bellum (If you want peace, prepare for war).", "Latin Proverb"],
    ["Sic Semper Tyrannis (Thus always to tyrants).", "Latin Phrase"],
    ["Sit on the bank of a river and wait: your enemy's corpse will soon float by.", "Umberto Eco, The Name of the Rose"],
    ["So little pains do the vulgar take in the investigation of truth, accepting readily the first story that comes to hand.", "Thucydides"],
    ["So teach us to number our days, that we may apply our hearts unto wisdom.", "Psalms, 90:12"],
    ["Socialism is a philosophy of failure, the creed of ignorance, and the gospel of envy, its inherent virtue is the equal sharing of misery.", "Winston Churchill"],
    ["Soldiers live. He dies and not you, and you feel guilty, because you're glad he died, and not you. Soldiers live, and wonder why.", "Croaker, Soldiers Live"],
    ["Some battles are won with swords and spears, others with quills and ravens.", "Tywin Lannister, A Storm of Swords"],
    ["Some ideas are so stupid that only intellectuals believe them.", "George Orwell"],
    ["Somebody asked me why I did not get an agreement with Colombia. They might just as well ask me why I do not nail cranberry jelly to the wall. It would not be my fault or the fault of the nail, it would be the fault of the jelly.", "Theodore Roosevelt"],
    ["Sometimes you have to take a step back to move forward.", "Unknown"],
    ["Speak of the devil and he doth appear.", "Idiom"],
    ["Speak softly and carry a big stick.", "Theodore Roosevelt"],
    ["Speak with contempt of none, from slave to king, The meanest Bee hath, and will use, a sting.", "Benjamin Franklin"],
    ["Speech is silver; silence is golden.", "Proverb"],
    ["Stand your ground. Don't fire unless fired upon, but if they mean to have a war, let it begin here!", "John Parker"],
    ["Stevenson had found that the secret of life lies in laughter and humility.", "G. K. Chesterton, Heretics"],
    ["Stop quoting laws, we carry weapons.", "Gnaeus Pompeius Magnus"],
    ["Strength does not come from physical capacity. It comes from an indomitable will.", "Mahatma Gandhi"],
    ["Style is the stuff you get wrong.", "Neil Gaiman"],
    ["Sweat saves blood.", "Erwin Rommel"],
    ["Take things as they come.", "Idiom"],
    ["Taught never to retreat, never to surrender. Taught that death on the battlefield in service to Sparta was the greatest glory he could achieve in his life.", "Dilios, 300"],
    ["Tell me with whom you consort and I will tell you who you are; if I know how you spend your time, then I know what might become of you.", "Johann Wolfgang von Goethe"],
    ["Tell my tale to those who ask. Tell it truly, the ill deeds along with the good, and let me be judged accordingly. The rest... is silence.", "Dinobot, Beast Wars: Transfomers"],
    ["Terrorism is the price of empire. If you do not wish to pay the price, you must give up the empire.", "Pat Buchanan"],
    ["The Catholic Church is an institution I am bound to hold divine – but for unbelievers a proof of its divinity might be found in the fact that no merely human institution conducted with such knavish imbecility would have lasted a fortnight.", "Hilaire Belloc"],
    ["The Empire's debts grow legion.", "Zargabaath, Final Fantasy XII"],
    ["The Horned Lord once said that sorcery is a sword without a hilt. There is no safe way to grasp it.", "Dalla, A Storm of Swords"],
    ["The LORD is a man of war: the LORD is his name.", "Exodus 15:3"],
    ["The Law is a fortress on a hill that armies cannot take or floods wash away.", "Muhammad"],
    ["The absurd is the essential concept and the first truth.", "Albert Camus"],
    ["The ancient Oracle said that I was the wisest of all the Greeks. It is because I alone, of all the Greeks, know that I know nothing.", "Socrates"],
    ["The arc of the moral universe is long but it bends toward justice.", "Martin Luther King Jr."],
    ["The art of war is of vital importance to the State. It is a matter of life and death, a road either to safety or to ruin. Hence it is a subject of inquiry which can on no account be neglected.", "Sun Tzu"],
    ["The art of war teaches us to rely not on the likelihood of the enemy's not coming, but on our own readiness to receive him; not on the chance of his not attacking, but rather on the fact that we have made our position unassailable.", "Sun Tzu"],
    ["The average man does not want to be free. He simply wants to be safe.", "H. L. Mencken"],
    ["The beatings will continue until morale improves.", "Unknown"],
    ["The beauty of the soul shines out when a man bears with composure one heavy mischance after another, not because he does not feel them, but because he is a man of high and heroic temper.", "Aristotle"],
    ["The beginning of all wisdom is wonder.", "Aristotle"],
    ["The best argument against democracy is a five-minute conversation with the average voter.", "Winston Churchill"],
    ["The best carpenters make the fewest chips.", "Proverb"],
    ["The best definition I have heard of modern warfare is, 'Months of boredom punctuated by moments of extreme terror.'", "Guy's Hospital Gazette"],
    ["The black wind howls.", "Magus, Chrono Trigger"],
    ["The body dies...but the spirit lives on.", "Zemus, Final Fantasy IV"],
    ["The brain is like a muscle. When it is in use we feel very good. Understanding is joyous.", "Carl Sagan"],
    ["The captain goes down with the ship.", "Maritime tradition"],
    ["The castle can be rebuilt, in time. It's not the walls that make a lord, it's the man.", "Stannis Baratheon, A Storm of Swords"],
    ["The child who is not embraced by the village will burn it down to feel its warmth.", "African Proverb"],
    ["The city is the teacher of the man.", "Simonides"],
    ["The common people pray for rain, healthy children, and a summer that never ends. It is no matter to them if the high lords play their game of thrones, so long as they are left in peace. They never are.", "Jorah Mormont, A Game of Thrones"],
    ["The correct analogy for the mind is not a vessel that needs filling, but wood that needs igniting.", "Plutarch"],
    ["The day of small nations has long passed away. The day of empires has come.", "Joseph Chamberlain"],
    ["The devil you know is better than the devil you don't know.", "Idiom"],
    ["The dreams of youth are the regrets of maturity.", "Lord of Darkness, Legend"],
    ["The enemy of my enemy is my friend.", "Ancient Proverb"],
    ["The engineer is judged by the end product which is not simply ideas. If he builds a building that collapses, it doesn't matter how brilliant his idea was. He is ruined. Conversely, if an intellectual who's brilliant has an idea for rearranging society and that ends in a disaster, he pays no price at all.", "Thomas Sowell"],
    ["The eyes believe themselves; the ears believe other people.", "German Proverb"],
    ["The fate of unborn Millions will now depend, under God, on the Courage and Conduct of this army--Our cruel and unrelenting enemy leaves us no choice but a brave resistance, or the most abject submission; this is all we can expect. We have therefore to resolve to conquer or die.", "George Washington"],
    ["The fear of the LORD is the beginning of wisdom: and the knowledge of the holy is understanding.", "Proverbs 9:10"],
    ["The first method for estimating the intelligence of a ruler is to look at the men he has around him.", "Niccolo Machiavelli"],
    ["The first skill a beginner should master is how to escape.", "Miyamoto Musashi"],
    ["The flame that burns twice as bright burns half as long.", "Eldon Tyrell, Blade Runner"],
    ["The fool strikes. The wise man smiles, and watches, and learns. Then strikes.", "Laithlin, Half a King"],
    ["The future belongs to those who prepare for it today.", "Malcolm X"],
    ["The future is not what it used to be.", "Yogi Berra"],
    ["The government is good at one thing. It knows how to break your legs, and then hand you a crutch and say, ‘See if it weren't for the government, you wouldn't be able to walk.’", "Harry Browne"],
    ["The grass is always greener on the other side of the fence.", "Idiom"],
    ["The greater the difficulty, the more glory in surmounting it.", "Epicurus"],
    ["The harder the conflict, the more glorious the triumph, What we obtain too cheaply, we esteem too lightly; it is dearness only that gives everything its value.", "Thomas Paine"],
    ["The height of originality is skill in concealing origins.", "Unknown"],
    ["The individual has always had to struggle to keep from being overwhelmed by the tribe. If you try it, you will be lonely often, and sometimes frightened. But no price is too high to pay for the privilege of owning yourself.", "Friedrich Nietzsche"],
    ["The intuitive mind is a sacred gift and the rational mind is a faithful servant. We have created a society that honours the servant but has forgotten the gift.", "Albert Einstein"],
    ["The journey of a thousand miles begins with a single step.", "Laozi"],
    ["The line separating good and evil passes not through states, nor between classes, nor between political parties either -- but right through every human heart -- and through all human hearts. This line shifts. Inside us, it oscillates with the years. And even within hearts overwhelmed by evil, one small bridgehead of good is retained.", "Aleksandr Solzhenitsyn"],
    ["The man who first flung a word of abuse at his enemy instead of a spear was the founder of civilisation.", "John Hughlings Jackson"],
    ["The man who has nothing can still have faith.", "Commander, Dawn of War"],
    ["The man who passes the sentence should swing the sword.", "Eddard Stark, Game of Thrones"],
    ["The man who reads nothing at all is better educated than the man who reads nothing but newspapers.", "Thomas Jefferson"],
    ["The mass of men lead lives of quiet desperation.", "Henry David Thoreau"],
    ["The mathematical sciences particularly exhibit order, symmetry, and limitation; and these are the greatest forms of the beautiful.", "Aristotle"],
    ["The medium is the message.", "Marshall McLuhan"],
    ["The meek shall inherit the Earth, but not its mineral rights.", "J. Paul Getty"],
    ["The most dangerous risk of all – the risk of spending your life not doing what you want on the bet you can buy yourself the freedom to do it later.", "Randy Komisa"],
    ["The nail that sticks out gets hammered down.", "Japanese Proverb"],
    ["The nation that will insist on drawing a broad line of demarcation between the fighting man and the thinking man is liable to find its fighting done by fools and its thinking done by cowards.", " William Francis Butler"],
    ["The needs of the many outweigh the needs of the few.", "Spock, Star Trek II: The Wrath of Khan"],
    ["The new electronic interdependence recreates the world in the image of a global village.", "Marshall McLuhan"],
    ["The next best thing to being witty one's self, is to be able to quote another's wit.", "Christian Nestell Bovee"],
    ["The night is darkest just before the dawn. And I promise you, the dawn is coming.", "Harvey Dent, The Dark Knight"],
    ["The night is far spent, the day is at hand: let us therefore cast off the works of darkness, and let us put on the armour of light.", "Romans 13:12"],
    ["The north remembers, and the mummer's farce is almost done.", "Wyman Manderly, A Dance with Dragons"],
    ["The obedient always think about themselves as virtuous, rather than cowardly.", "Robert Anton Wilson"],
    ["The only place success comes before work is in the dictionary.", "Vince Lombardi"],
    ["The only rules that really matter are these: what a man can do and what a man can't do.", "Jack Sparrow, Pirates of the Caribbean"],
    ["The only thing that saves us from the bureaucracy is its inefficiency.", "Eugene McCarthy"],
    ["The only thing we have to fear is fear itself.", "Franklin Delano Roosevelt"],
    ["The only way to deal with an unfree world is to become so absolutely free that your very existence is an act of rebellion.", "Albert Camus"],
    ["The past can bind a man as surely as irons.", "Reddas, Final Fantasy XII"],
    ["The pen is mightier than the sword.", "Cardinal Richelieu, Richelieu; Or the Conspiracy"],
    ["The physician can bury his mistakes, but the architect can only advise his client to plant vines.", "Frank Lloyd Wright"],
    ["The price of freedom is eternal vigilance.", "John Philpot Curran"],
    ["The psychotic drowns in the same waters in which the mystic swims with delight.", "Joseph Campbell"],
    ["The race is not always to the swift.", "Aesop"],
    ["The real man smiles in trouble, gathers strength from distress, and grows brave by reflection.", "Thomas Paine"],
    ["The reaper is always one step behind me.", "Shadow, Final Fantasy VI"],
    ["The release of atomic energy has not created a new problem. It has merely made more urgent the necessity of solving an existing one.", "Albert Einstein"],
    ["The road to hell is paved with adverbs.", "Stephen King"],
    ["The rocket worked perfectly, except for landing on the wrong planet.", "Wernher von Braun on the V-2 Rocket"],
    ["The role of a writer is not to say what we can all say, but what we are unable to say.", "Anais Nin"],
    ["The secret to life is to die before you die.", "Eckhart Tolle"],
    ["The shadow of Rome is vast, and you, Thracian, will die under it.", "Glaber to Spartacus, Spartacus"],
    ["The shepherd must tend his flock, and at times, fight off the wolves.", "Reverend Oliver, The Patriot"],
    ["The smallest minority on earth is the individual. Those who deny individual rights, cannot claim to be defenders of minorities.", "Ayn Rand"],
    ["The speed of communications is wondrous to behold. It is also true that speed can multiply the distribution of information that we know to be untrue.", "Edward R. Murrow"],
    ["The strong do what they can, the weak suffer what they must.", "Thucydides"],
    ["The temple is like no other building in the world. It has towers and decoration and all the refinements which the human genius can conceive of.", "Antonio da Magdalena"],
    ["The tree of liberty must be refreshed from time to time with the blood of patriots and tyrants.", "Thomas Jefferson"],
    ["The true test of civilization is, not the census, nor the size of cities, nor the crops - no, but the kind of man the country turns out.", "Ralph Waldo Emerson"],
    ["The truth is something that burns. It burns off dead wood. And people don't like having the dead wood burnt off, often because they're 95 percent dead wood.", "Jordan B. Peterson"],
    ["The tyrant will always find a pretext for his tyranny, and it is useless for the innocent to try by reasoning to get justice, when the oppressor intends to be unjust.", "Aesop"],
    ["The unexamined life is not worth living.", "Socrates"],
    ["The urge to save humanity is almost always only a false-face for the urge to rule it.", "H. L. Mencken"],
    ["The victorious strategist only seeks battle after the victory has been won, whereas he who is destined to defeat first fights and afterwards looks for victory.", "Sun Tzu"],
    ["The weak are always anxious for justice and equality. The strong pay no heed to either.", "Aristotle"],
    ["The weakest of all weak things is a virtue that has not been tested in the fire.", "Mark Twain"],
    ["The winds and the waves are always on the side of the ablest navigators.", "Edward Gibbon"],
    ["The wise tell us that a nail keeps a shoe, a shoe keeps a horse, a horse keeps a knight, a knight, who can fight, keeps a castle.", "Freidank"],
    ["The world breaks everyone and afterward many are strong at the broken places. But those that will not break it kills. It kills the very good and the very gentle and the very brave impartially. If you are none of these you can be sure it will kill you too but there will be no special hurry.", "Ernest Hemingway"],
    ["Their rising all at once was as the sound of a thunder heard remote.", "John Milton"],
    ["Then said Jesus unto him, ‘Put up again thy sword into his place: for all they that take the sword shall perish with the sword.’", "Matthew 26:52"],
    ["There are deeper, older laws: the younger brother bows before the elder.", "Stannis Baratheon, Robert's Rebellion (Histories & Lore)"],
    ["There are known knowns; there are things we know we know. We also know there are known unknowns; that is to say we know there are some things we do not know. But there are also unknown unknowns - the ones we don't know we don't know.", "Donald Rumsfeld"],
    ["There are many like you, good men in service to bad causes.", "Varys, A Dance with Dragons"],
    ["There are no men like me. There's only me.", "Jaime Lannister, Game of Thrones"],
    ["There are no rationalists. We all believe fairy-tales, and live in them.", "G. K. Chesterton"],
    ["There are no true knights, no more than there are gods. If you can't protect yourself, die and get out of the way of those who can. Sharp steel and strong arms rule this world, don't ever believe any different.", "Sandor Clegane, A Clash of Kings"],
    ["There are no two words in the English language more harmful than good job.", "Terence Fletcher, Whiplash"],
    ["There are those who seek knowledge for the sake of knowledge; that is Curiosity. There are those who seek knowledge to be known by others; that is Vanity.There are those who seek knowledge in order to serve; that is Love.", "Bernard of Clairvaux"],
    ["There are three sides to every story: your side, my side, and the truth.", "Robert Evans"],
    ["There are three things all wise men fear: the sea in storm, a night with no moon, and the anger of a gentle man.", "Patrick Rothfuss, The Name of the Wind"],
    ["There are two rules for being successful in martial arts. Rule 1: Never tell others everything you know.", "Unknown"],
    ["There are very few personal problems that cannot be solved through a suitable application of high explosives.", "Scott Adams"],
    ["There can be no triumph without loss. No victory without suffering. No freedom without sacrifice.", "The Lord of the Rings: The Return of the King"],
    ["There can be no true despair without hope.", "Bane, The Dark Knight Rises"],
    ["There can only be one.", "Motto of the Immortals, Highlander"],
    ["There is a God-shaped vacuum in the heart of each man which cannot be satisfied by any created thing but only by God the Creator, made know through Jesus Christ.", "Blaise Pascal"],
    ["There is a great deal of ruin in a nation.", "Adam Smith"],
    ["There is a tool for every task, and a task for every tool.", "Tywin Lannister, A Storm of Swords"],
    ["There is no better than adversity. Every defeat, every heartbreak, every loss, contains its own seed, its own lesson on how to improve your performance next time.", "Malcolm X"],
    ["There is no creature on earth half so terrifying as a truly just man.", "Varys, A Game of Thrones"],
    ["There is no decent place to stand in a massacre.", "Leonard Cohen"],
    ["There is no excellent beauty that hath not some strangeness in the proportion.", "Francis Bacon"],
    ["There is no female Mozart because there is no female Jack the Ripper.", "Camille Paglia"],
    ["There is no substitute for a militant freedom. The only alternative is submission and slavery.", "Calvin Coolidge"],
    ["There is no such thing as innocence, only degrees of guilt.", "Librarian, Dawn of War"],
    ["There is nothing more deceptive than an obvious fact.", "Sherlock Holmes, The Boscombe Valley Mystery"],
    ["There is nothing noble in being superior to your fellow man; true nobility is being superior to your former self.", "Ernest Hemmingway"],
    ["There is only one god, death and there is only one thing you say to him, not today.", "Syrio Forel, A Game of Thrones"],
    ["There is only one good, knowledge, and one evil, ignorance.", "Socrates"],
    ["There never was a good knife made of bad steel.", "Benjamin Franklin"],
    ["There's a fundamental connection between seeming and being. We understand how dangerous a mask can be. We all become what we pretend to be.", "Kvothe, The Name of the Wind"],
    ["There's always another secret.", "Kelsier, Mistborn: The Final Empire"],
    ["These are the times that try men's souls.", "Thomas Paine"],
    ["Things always seem fairer when we look back at them, and it is out of that inaccessible tower of the past that Longing leans and beckons.", "James Russell Lowell"],
    ["Think not that I am come to send peace on earth: I came not to send peace, but a sword.", "Matthew 10:34"],
    ["This is how you start a war. Not with a crown of gold, but with a blade of steel.", "Gerold Dayne, A Feast for Crows"],
    ["This life of man appears for a short space, but of what went before, or what is to follow, we are utterly ignorant.", "Bede"],
    ["This nation was founded on one principle above all else: The requirement that we stand up for what we believe, no matter the odds or the consequences. When the mob and the press and the whole world tell you to move, your job is to plant yourself like a tree beside the river of truth, and tell the whole world -- 'No, YOU move.'", "Captain America, The Amazing Spider-Man: Civil War"],
    ["Those that rule must hear and be deaf, must see and be blind.", "German Proverb"],
    ["Those who cannot remember the past are condemned to repeat it.", "George Santayana"],
    ["Those who lose dreaming are lost.", "Australian Aboriginal Proverb"],
    ["Those who need leaders are not qualified to choose them.", "Michael Malice"],
    ["Those without swords can still die upon them.", "Eowyn, The Two Towers"],
    ["Thou shalt not muzzle the ox when he treadeth out the corn.", "Deuteronomy, 25:4"],
    ["Three things are necessary for the salvation of man: to know what he ought to believe; to know what he ought to desire; and to know what he ought to do.", "Saint Thomas Aquinas"],
    ["Three things are to be looked to in a building: that it stand on the right spot; that it be securely founded; that it be successfully executed.", "Johann Wolfgang von Goethe"],
    ["Time and tide wait for no man.", "Geoffrey Chaucer"],
    ["Time crumbles things; everything grows old and is forgotten under the power of time.", "Aristotle"],
    ["Time is a great teacher, but unfortunately it kills all its pupils.", "Hector Berlioz"],
    ["Time is the most valuable thing a man can spend.", "Theophrastus"],
    ["Titles do seem to breed titles.", "Petyr Baelish, Game of Thrones"],
    ["To achieve great things, two things are needed: a plan, and not quite enough time.", "Leonard Bernstein"],
    ["To be a champion, compete; to be a great champion, compete with the best; but to be the greatest champion, compete with yourself.", "Matshona Dhliwayo"],
    ["To err is human, to forgive divine.", "Alexander Pope"],
    ["To fight and conquer in all your battles is not supreme excellence; supreme excellence consists in breaking the enemy's resistance without fighting.", "Sun Tzu"],
    ["To progress again, man must remake himself. And he cannot remake himself without suffering. For he is both the marble and the sculptor. In order to uncover his true visage he must shatter his own substance with heavy blows of his hammer.", "Alexis Carrel"],
    ["To the last, I grapple with thee; From Hell's heart, I stab at thee; For hate's sake, I spit my last breath at thee.", "Captain Ahab, Moby Dick"],
    ["To the mind that is still, the whole universe surrenders.", "Laozi"],
    ["Tomorrow can redeem any failure and it can undermine any success.", "John Danaher"],
    ["Tradition is not the worship of ashes but the preservation of fire.", "Gustav Mahler"],
    ["Treade a worme on the tayle, and it must turne agayne.", "John Heywood"],
    ["Truth begins in lies.", "Gregory House, House M.D."],
    ["Truth is treason in an empire of lies.", "George Orwell"],
    ["Truth, she thought. As terrible as death. But harder to find.", "Juliana  Crain, The Man in the High Castle"],
    ["Try first thyself, and after call in God; For to the worker God himself lends aid.", "Euripides"],
    ["Two wrongs do not make a right.", "Idiom"],
    ["Ultima ratio regum (The last  argument of kings).", "Latin Proverb engraved on the cannons of King Louis XIV"],
    ["Uneasy lies the head that wears a crown.", "King Henry IV, Henry IV, Part 2."],
    ["Variety is the spice of life.", "Proverb"],
    ["Veni, vidi, vici (I came, I saw, I conquered).", "Julius Caesar"],
    ["Violence sings its own song.", "Michael Malice"],
    ["Virtue is its own reward.", "Proverb"],
    ["Vision is the art of seeing things invisible.", "Jonathan Swift"],
    ["Vox populi, vox Dei (The voice of the people is the voice of God).", "Latin Proverb"],
    ["War is coming, In all it's glory, and all it's horror.", "Arcturus Mengsk, StarCraft II: Wings of Liberty"],
    ["War is cruelty. There is no use trying to reform it. The crueler it is, the sooner it will be over.", "William Tecumseh Sherman"],
    ["War is merely the continuation of politics by other means.", "Carl von Clausewitz"],
    ["War is nothing but a duel on a larger scale.", "Carl von Clausewitz"],
    ["War is the health of the state.", "Randolph Bourne"],
    ["War is young men dying and old men talking.", "Odysseus, Troy"],
    ["War therefore is an act of violence to compel our opponent to fulfill our will.", "Carl von Clausewitz"],
    ["Wars may be fought with weapons, but they are won by men. It is the spirit of the men who follow and of the man who leads that gains the victory.", "George S. Patton"],
    ["Waste not, want not.", "Proverb"],
    ["Watch and pray so that you will not fall into temptation. The spirit is willing, but the flesh is weak.", "Matthew 26:41"],
    ["We are what we repeatedly do. Excellence, then, is not an act, but a habit.", "Aristotle"],
    ["We believe that the Anarchists are real enemies of Marxism.", "Joseph Stalin"],
    ["We come into the world alone and we die alone. Why, in life, should we be any less alone?", "Diogenes"],
    ["We do not choose our destinies. Yet we must...we must do our duty, no? Great or small, we must do our duty.", "Stannis Baratheon, A Storm of Swords"],
    ["We do not kneel.", "Mance Rayder, Game of Thrones"],
    ["We hang the petty thieves and appoint the great ones to public office.", "Aesop"],
    ["We have now sunk to a depth at which restatement of the obvious is the first duty of intelligent men.", "George Orwell"],
    ["We march to victory or we march to defeat, but we go forward, only forward. We will liberate Winterfell or die in the attempt.", "Stannis Baratheon, A Game of Thrones"],
    ["We may test the hypothesis that the State is largely interested in protecting itself rather than its subjects by asking: which category of crimes does the State pursue and punish most intensely, those against private citizens or those against itself?", "Murray Rothbard"],
    ["We often give our enemies the means for our own destruction.", "Aesop"],
    ["We only live to discover beauty. All else is a form of waiting.", "Kahlil Gibran"],
    ["We only live to discover beauty. All else is a form of waiting.", "Kahlil Gibran"],
    ["We should forgive our enemies, but not before they are hanged.", "Heinrich Heine"],
    ["We think that a powerful and vigorous movement is impossible without differences - 'true conformity' is possible only in the cemetery.", "Joseph Stalin"],
    ["Well begun is half done.", "Aristotle"],
    ["What a good artist understands is that nothing comes from nowhere. All creative work builds on what came before. Nothing is completely original.", "Austin Kleon"],
    ["What am I to do with those who would oppose me...but show them death?", "Vayne Solidor, Final Fantasy XII"],
    ["What does Stannis offer you? Vengeance. Vengeance for my sons and yours, for your husbands and your fathers and your brothers. Vengeance for your murdered lord, your murdered king, your butchered princes. Vengeance.", "Davos Seaworth, A Dance with Dragons"],
    ["What has been will be again,<br>what has been done will be done again;<br>there is nothing new under the sun.", "Ecclesiastes 1:9"],
    ["What the eye doesn't see, the heart doesn't grieve over.", "Proverb"],
    ["What you see and what you hear depends a great deal on where you are standing. It also depends on what sort of person you are.", "C. S. Lewis"],
    ["Whatever we achieve inwardly will change outer reality.", "Otto Rank"],
    ["Whatever weapon you design, your enemies will one day possess.", "Unknown"],
    ["When Atlas begged Zeus for mercy, he did not ask for the King of Olympus to lighten the weight of the world, he asked him to make his shoulders broader to be able to carry the heavy world better.", "Greek Proverb"],
    ["When I am weaker than you, I ask you for freedom because that is according to your principles; when I am stronger than you, I take away your freedom because that is according to my principles.", "Leto II, Dune"],
    ["When I voted, my equality tumbled into the box with my ballot; they disappeared together.", "Louis Veuillot"],
    ["When a dog goes bad, the fault lies with his master.", "Kevan Lannister, A Feast for Crows"],
    ["When a dove begins to associate with crows its feathers remain white but its heart grows black.", "German Proverb"],
    ["When goods don't cross borders, soldiers will.", "Frederic Bastiat"],
    ["When injustice becomes law, rebellion becomes duty.", "Thomas Jefferson"],
    ["When people get used to preferential treatment, equal treatment seems like discrimination.", "Thomas Sowell"],
    ["When soldiers lack discipline, the fault lies with their commander.", "Tywin Lannister, Game of Thrones"],
    ["When the legend becomes fact, print the legend.", "Maxwell Scott, The Man Who Shot Liberty Valance"],
    ["When the snows fall and the white winds blow, the lone wolf dies but the pack survives.", "Eddard Stark, A Game of Thrones"],
    ["When the word leader, or leadership, returns to current use, it connotes a relapse into barbarism. For a civilized people, it is the most ominous word in any language.", "Isabel Paterson"],
    ["When you do things right, people won't be sure you've done anything at all.", "Futurama"],
    ["When you play the game of thrones, you win or you die. There is no middle ground.", "Cersei Lannister, A Game of Thrones"],
    ["When you pray for rain, you gotta deal with the mud too.", "Robert McCall, The Equalizer"],
    ["When you recognize ill will, speak out against ill will, and grant no peace to your foes.", "Havamal"],
    ["When you vote, you are exercising political authority, you're using force. And force, my friends, is violence. The supreme authority from which all other authorities are derived.", "Robert A. Heinlein, Starship Troopers"],
    ["When your enemies defy you, you must serve them steel and fire. When they go to their knees, however, you must help them back to their feet. Elsewise no man will ever bend the knee to you.", "Tywin Lannister, A Storm of Swords"],
    ["When your friends betray you, sometimes the only people you can trust are strangers.", "Danny Roman, The Negotiator"],
    ["Where does a wise man hide a leaf? In the forest. But what does he do if there is no forest? He grows a forest to hide it in.", "G. K. Chesterton"],
    ["Where the battle rages, there the loyalty of the soldier is proved.", "Martin Luther"],
    ["Where there are too many policemen, there is no liberty. Where there are too many soldiers, there is no peace. Where there are too many lawyers, there is no justice.", "Lin Yutang"],
    ["Where there is a will, there is a way.", "Proverb"],
    ["Where there is only a choice between cowardice and violence, I would advise violence.", "Mohandas Gandhi"],
    ["Where tillage begins, other arts follow. The farmers therefore are the founders of human civilization.", "Daniel Webster"],
    ["Wherever you look, there is something to be seen.", "Talmud"],
    ["Who asks whether the enemy were defeated by strategy or valor?", "Virgil"],
    ["Who trusted God was love indeed<br>And love Creation's final law<br>Tho' Nature, red in tooth and claw<br>With ravine, shriek'd against his creed.", "Alfred Tennyson, In Memoriam A. H."],
    ["Whoever appeals to the law against his fellow man is either a fool or a coward. Whoever cannot take care of himself without this law, is both. For a wounded man shall say to his assailant: ‘If I live, I will kill you. If I die, then you are forgiven.’ Such, is the rule of honor.", "Omerta, Lamb of God"],
    ["Whoever desires to found a state and give it laws, must start with assuming that all men are bad and ever ready to display their vicious nature, whenever they may find occasion for it.", "Niccolo Machiavelli"],
    ["Whoever destroys a soul, it is considered as if he destroyed an entire world. And whoever saves a life, it is considered as if he saved an entire world.", "Mishnah Sanhedrin 4:5"],
    ["Whoso pulleth out this sword of this stone and anvil, is right wise king born of all England.", "The Archbishop of Canterbury, King Arthur And His Knights"],
    ["Why do people insist on creating things that will inevitably be destroyed? Why do people cling to life, knowing that they must someday die?...Knowing that none of it will have meant anything once they do?", "Kefka Palazzo, Final Fantasy VI"],
    ["Why do you build, knowing destruction is inevitable? Why do you yearn to live, knowing all things must die?", "Kefka Palazzo, Final Fantasy VI"],
    ["Why is it always the innocents who suffer most, when you high lords play your game of thrones?", "Varys, A Game of Thrones"],
    ["Winning isn't everything, it's the only thing.", "Henry Russell Sanders"],
    ["Wisdom and virtue are like the two wheels of a cart.", "Japanese Proverb"],
    ["With each passing day, the world finds new and exciting ways to kill a man.", "Balthier, Final Fantasy XII"],
    ["With respect to the requirements of art, a probable impossibility is to be preferred to a thing improbable and yet possible.", "Aristotle"],
    ["Without order nothing can exist - without chaos nothing can evolve. Nowadays people know the price of everything and the value of nothing.", "Oscar Wilde"],
    ["Without purpose, we would not exist. It is purpose that created us. Purpose that connects us. Purpose that pulls us. That guides us. That drives us. It is purpose that defines us. Purpose that binds us. We are here because of you, Mr Anderson. We're here to take from you what you tried to take from us. Purpose.", "Agent Smith to Neo, The Matrix Reloaded"],
    ["Woe unto them that call evil good, and good evil; that put darkness for light, and light for darkness; that put bitter for sweet, and sweet for bitter!", "Isaiah 5:20"],
    ["Words are wind.", "Tyrion Lannister, A Storm of Swords"],
    ["Words are, in my not-so-humble opinion, our most inexhaustible source of magic. Capable of both inflicting injury, and remedying it.", "Albus Dumbledore, Harry Potter and the Deathly Hallows"],
    ["Words offer the means to meaning, and for those who will listen, the enunciation of truth.", "V, V for Vendetta"],
    ["Would you tell me, please, Mister Howard, why should I trade one tyrant three thousand miles away for three thousand tyrants one mile away?", "Benjamin Martin, The Patriot"],
    ["Ya gotta look out for number one, but don't step in number two.", "Thornton Mellon, Back to School"],
    ["You called down the thunder, now reap the whirlwind!", "Ghost, StarCraft"],
    ["You can fool all the people some of the time, and some of the people all the time, but you cannot fool all the people all the time.", "Abraham Lincoln"],
    ["You can't cheat an honest man.", "Proverb"],
    ["You cannot understand what it is to live as long as I have. To know all that I know. You people are dead in the blink of an eye, and have to be taught the same old lessons all over the again. The same lessons that Juvens taught Stolicus a thousand years ago. It becomes extremely tiresome.", "Bayaz, Last Argument of Kings"],
    ["You don't get to choose not to pay a price, you only get to choose which price you pay.", "Jordan B. Peterson"],
    ["You gotta make the money first. Then when you get the money, you get the power. Then when you get the power, then you get the women.", "Tony Montana, Scarface"],
    ["You have as much laughter as you have faith.", "Martin Luther"],
    ["You have power over your mind - not outside events. Realize this, and you will find strength.", "Marcus Aurelius"],
    ["You have to realistic about these things.", "Logen Ninefingers, Last Argument of Kings"],
    ["You kill for sport, and hide your fear behind a wall of bravado. Now let me show you true fear!", "Soren, Fire Emblem: Path of Radiance"],
    ["You know my brother once told me? That nothing someone says before the word but really counts.", "Benjen Stark, Game of Thrones"],
    ["You should laugh every moment you live, for you'll find it decidedly difficult afterwards.", "Joe Abercrombie, Best Served Cold"],
    ["You spoony bard!", "Tellah, Final Fantasy IV"],
    ["You were a hero 'round these parts. That's what they call you when you kill so many people the word murderer falls short.", "Sajaam of Monza Murcatto, Best Served Cold"],
    ["Your failing as a son, is my failing as a father", "Marcus Aurelius, Gladiator"],
    ["Your lives are forfeit, and your insurgence with them. Dalmasca will again know order.", "Vayne Solidor, Final Fantasy XII"],
    ["Your resistance is futile, I rise again!", "Rampage, Beast Wars: Transfomers"],
    ["Your scientists were so preoccupied with whether or not they could, they didn't stop to think if they should.", "Ian Malcolm, Jurassic Park"],
    ["Your shield is shattered! Your oaths poison those you would protect!", "Gabranth, Final Fantasy XII"],
    ["‘We need’ is always code for ‘I want.’", "Michael Malice"]
    ["Some cause happiness wherever they go; others whenever they go.", "Oscar Wilde"],
    ["", ""],
    ["", ""],
    ["", ""],
    ["", ""],
    ["", ""],
    ["", ""],
    ["", ""],
    ["", ""],
    ["", ""],
    ["", ""],
    ["", ""],
    ["", ""],
    ["", ""],
];

function displayQuote() {
	var rand = Math.floor(Math.random() * (quotesArray.length));
	document.getElementById('quote').innerHTML = "<h2>\"" + quotesArray[rand][0] + "\"</h2>" + "- " + quotesArray[rand][1];
}
