name: Test Website

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      # - name: Install ESLint
      #   run: npm install -g eslint

      # - name: Run ESLint
      #   run: npm run lint

      - name: Install Lighthouse
        run: npm install -g lighthouse

      - name: Update Apt Cache
        run: sudo apt update
      
      - name: Download Google Chrome
        run: wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb

      - name: Install Google Chrome
        run: sudo apt install -y ./google-chrome-stable_current_amd64.deb

      - name: Run Lighthouse Audit
        run: lighthouse --output=htnml --output-path=./lighthouse-report.html --save-assets --chrome-flags="--headless --no-sandbox" https://www.derekmelder.com/

      - name: Save Report
        uses: actions/upload-artifact@v3
        with:
          name: lighthouse-report
          path: lighthouse-report.html